### ISSUE TITLE
Home page redesign

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#1012]

**Comment by vikpak89** [comment]
Creating  two options of Home Page
https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=3393-12544&t=64AKPg4OKsiHBuiL-1

**Comment by vdruda** [comment]
Done
