### ISSUE TITLE
UX/UI: User page collections buttons: Title "Наставнические" isn't fully visible

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1054]
Preconditions
Any user's page is open. Russian language is chosen

Steps
Check the “Mentoring” button 

Expected result
Title "Наставнические" is fully visible

Actual result
Title "Наставнические" isn't fully visible

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/e6b7258c-19a3-4707-b2bb-d4ea9236e2d6)

**Comment by algrinkevich** [comment]
@evgenia7p it seems the issue has been fixed. Could you check this again?

**Comment by evgenia7p** [comment]
@algrinkevich Yes, you are right, I'll close this issue
