### ISSUE TITLE
Align design for components

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#1057]
Check and update design of all components (check tokens)

- [x] Button (@algrinkevich)
- [x] Checkbox (@AKiroi)
- [x] InProgress (@AKiroi)
- [x] Input (@AKiroi)
- [x] Tooltip (@AKiroi, @Ekaterina1994 )
- [x] Toggle (@AKiroi)
- [x] Tags (@algrinkevich)
- [x] Select (@AKiroi)
- [x] Links (@algrinkevich)
- [x] Dropdown (@AKiroi)
- [x] Accoerdion (@algrinkevich)
- [x] Avatar  (@AKiroi)
- [x] Footer (@algrinkevich )
- [x] Header (@AKiroi)
- [ ]

**Comment by Ekaterina1994** [comment]
Done

**Comment by n144astya** [comment]
done
