### ISSUE TITLE
Day Reports: Checkboxes for marking plan and problem as completed are different

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1097]
Preconditions
User is authorized. User's way is created and opened. Some day reports with plan and problem exist 

Steps
Visually compare checkboxes for marking plan and problem as completed

Expected result
Checkboxes in Plans and Problems blocks look similar

Actual result
Checkboxes in Plans and Problems blocks are different

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/d92684ec-6bb0-4c42-af6c-d5bf7f6c469e)

**Comment by timoxa20** [comment]
The error corrected itself.

**Comment by evgenia7p** [comment]
Checked
