### ISSUE TITLE
User personal data: Cursor is displayed incorrectly

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1099]
Preconditions
User personal area page is opened

Steps
1.	Hover over user name
2.	Hover over e-mail
3.	Hover over ‘Mentor’ word
4.	Hover over ‘No tags’ phrase
5.	Hover over 'About' word
6.	Hover over 'About' line

Expected result
The text cursor must be enabled only in the user name and 'About' lines

Actual result
The text cursor is enabled in the user name, e-mail, ‘Mentor’ word, ‘No tags’ phrase, 'About' word and 'About' line

https://github.com/tritonJS826/masters-way/assets/163824877/793526a0-c75c-42df-b324-2064a4976c26

**Comment by Ekaterina1994** [comment]
Deprecated. It's not a bug

**Comment by vdruda** [comment]
Done. Not a bug, remove to Done.
