### ISSUE TITLE
Day Reports: Large number of added labels don’t fit into a Jobs done and Plans sections

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1100]
Preconditions
User is authorized. User's way is created and opened. More than five different jobs done labels exist. Day report with job done and plan exists

Steps
1. Click on "Add label" in the Jobs done section 
2. Add four or more labels to the job done 
3. Repeat it with Plans section

Expected result
Large number of added labels fit into a Jobs done and Plans sections

Actual result
More than three or four added labels don’t fit into a Jobs done and Plans sections and overlap other sections

https://github.com/tritonJS826/masters-way/assets/163824877/d89c9453-075e-4519-b74a-eb246658e924

**Comment by Ekaterina1994** [comment]
Done

**Comment by n144astya** [comment]
done
