### ISSUE TITLE
Migrate from firebase analytics to google analytics

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#1103]
It could help us to decrease bundle size for 500-700Kb - improve first loading speed and also it will decread bandwidth cinsumption (we could save some money in future - longer usage of free tier on netlify CDN).

**Comment by tritonJS826** [comment]
Does it possible to migrate also all data or we should start to collect it from zero? Let's investigate

**Comment by Ekaterina1994** [comment]
Done
