### ISSUE TITLE
Align styles for labels modal

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#1106]
Ignore Color picker  (issue #1107 )

https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=1485-2497&t=C698TaZFgwDoyCcH-4

Prototype is https://github.com/tritonJS826/masters-way/labels (responsive partly as in github or your own variant)

**Comment by n144astya** [comment]
Done
