### ISSUE TITLE
Home Page: Read Manifesto link text disappears when hovering over it

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#1132]
## Steps to reproduce

1. Open Home page.
2. Scroll to Read Manifesto link.
3. Hover mouse over the link.

## Actual result

Read Manifesto link text blends into the background and is not visible.

## Expected result

Read Manifesto link text is visible.

## Comment:
The link is not highlighted initially - it looks like regular text.

https://github.com/tritonJS826/masters-way/assets/115548501/a53cb310-b3c9-4712-98aa-77256f02a06a

**Comment by vikpak89** [comment]
https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=408-4243&t=tERfHRrHWvCrb68p-1
