### ISSUE TITLE
Home page: click on Start for free, Try now buttons opens page "404 Not Found"

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#1133]
## Steps to reproduce

1. Open Home page.
2. Click Start for free!, Try now! buttons.

## Actual result
Open https://mastersway.netlify.app/[object%20Object]/auth/google with "404 Not Found".

## Expected result

Opens the registration modal window.

https://github.com/tritonJS826/masters-way/assets/115548501/9b2cd4e7-988e-483d-83ee-86644fb9c4b8

**Comment by Ekaterina1994** [comment]
Fixed

**Comment by vdruda** [comment]
Done
