### ISSUE TITLE
All ways in a table view: Status completed doesn’t work

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1145]
Preconditions
All ways page opened in a table view

Steps
1.	Click the Status select and set Completed from the dropdown menu
2.	Check the Status column 

Expected result
Only completed ways are displayed

Actual result
Abandoned and ways in progress are demonstrated as completed ways  

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/44a23cd3-2071-47df-a4fd-52553648b243)

**Comment by vdruda** [comment]
Preconditions
All ways page opened in a table view

Steps

Click the Status select and set Completed from the dropdown menu
Check the Status column
Expected result
Only completed ways are displayed

Actual result
Abandoned and ways in progress are demonstrated as completed ways

![Image](https://github.com/tritonJS826/masters-way/assets/141385609/208cdbab-67b7-4b4d-aa4c-eb64d2027507)

**Comment by vdruda** [comment]
Done

**Comment by AKiroi** [comment]
![Image](https://github.com/tritonJS826/masters-way/assets/112805668/814db318-b819-49c9-b591-78d873590de5)

**Comment by vdruda** [comment]
![2](https://github.com/tritonJS826/masters-way/assets/141385609/908fb3aa-ff88-4a95-baa0-498f1ff0757a)

Done
