### ISSUE TITLE
[All Ways] The cursor closes the tooltip when hovering over an element on the Description, reports, likes, "All Ways" page in card mode

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#1176]
### Environment  "Windows 10 10.0.19045.4412
Google Chrome 126.0.6478.115"
### Preconditions
All ways page is opened in a card view. At least one way exists in the All Ways cards.
### Reproduction steps
1. Hover over cursor the Description
2. Hover over cursor the reports
3. Hover over cursor the likes

### Actual result
The cursor closes the tooltip

Expected Result
The tooltip is fully visible and easy to read

![Image](https://github.com/tritonJS826/masters-way/assets/142949669/af488a5e-d633-4c99-a363-5fb1b80ff226)

**Comment by Ekaterina1994** [comment]
Good enough for now
