### ISSUE TITLE
Home page header: buttons are not clickable

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#1183]
## Steps to reproduce

1. Open home page on mobile.
2. Click any header buttons.

## Actual result

The buttons do not respond to clicks on them, there do not navigate to the corresponding page, the navigation menu does not open.

## Expected result

After clicking on any header elements, the corresponding page or the navigation menu opens.

https://github.com/tritonJS826/masters-way/assets/115548501/280029f4-298d-4d04-9a94-653efeb59e3f

## Comment: 
The same for web version with devtools opened.

**Comment by tritonJS826** [comment]
Done

**Comment by vdruda** [comment]
Done
