### ISSUE TITLE
Home page: Webpage layout (text + elements) shifted unpredictably

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1189]
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/cef82479-aad5-402b-b06d-fbda8d462125)

**Comment by Ekaterina1994** [comment]
Can't reproduce bug. Maybe was fixed after updated texts

**Comment by evgenia7p** [comment]
I get it and will close the issue
