### ISSUE TITLE
User personal data: Avatar blends into the background

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1190]
Preconditions
User is authorized. Personal area page is open

Steps
Check the avatar of the user in the top left corner

Expected result
Avatar color in a circle form is different from background color

Actual result
Avatar blends into the background

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/12bb28bc-9915-4ae7-8f6b-cd497c19cf37)

**Comment by Ekaterina1994** [comment]
We don't have avatar in components in the maket in figma. It's not a business requirement that background should not repeat color of layer.  Also after updating login new users have colored avatars (as in google account). So I'm not sure that we need customize old user's abatars. If need -   Move issue to design columns

**Comment by vikpak89** [comment]
created components for Avatars of different sizes
https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=4190-9892&t=HlcH20UrrMgqhBaJ-1



![Image](https://github.com/tritonJS826/masters-way/assets/167992048/e34ce37f-8623-4eb0-a035-ee864f987c6f)

**Comment by timoxa20** [comment]
Add a frame for the avatar so that it is the same on each page and does not match the background color

**Comment by vikpak89** [comment]
added frames to avatars
https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=4190-9892&t=egAB04ZUjesdvhYB-1

**Comment by Ekaterina1994** [comment]
done

**Comment by evgenia7p** [comment]
Checked
