### ISSUE TITLE
Language: Text of message “Mentors requests of the way”, buttons “Accept” and “Decline” in dialogue box aren’t translated into Russian, Ukrainian and Georgian languages

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1240]
Preconditions
The user is already authorized. Mentee way page exists

Steps
1. Open the way of mentee as a mentor
2. Click on the "Apply as Mentor" button
3. Check the way as a mentee in each language

Expected result
Window box with a text “Mentors requests of the way”, buttons “Accept” and “Decline” appears in mentee’s way and text and titles are shown in Russian, Ukrainian and Georgian languages according to the chosen language

Actual result
Window box with a text “Mentors requests of the way”, buttons “Accept” and “Decline” appears in mentee’s way and text and titles are shown in English regardless of chosen language

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/432fcceb-20ff-4c50-bd1a-efa01285e1ec)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/6fadc25c-9e1d-4ca6-bf91-2c3fac9dd5e9)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/bee292c9-c568-454f-90dc-cc67c79eeb01)

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
