### ISSUE TITLE
Create chat 1:1

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#1246]

**Comment by vikpak89** [comment]
На данный момент простой вариант чата, позже можно будет его модифицировать
https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=4555-3287&t=Upmq1yMh4wdPQVbG-1

![Image](https://github.com/user-attachments/assets/e03ea2fd-1a7e-4e89-acfc-ffb542842860)

**Comment by Ekaterina1994** [comment]
Done.
