### ISSUE TITLE
ADd pagination to Way page for Day Reports

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#1254]
- [x] (5 days) create new endpoint get 7 last day reports in the way request,
- [x] (2 days) add pagination logic
- [x] (5 days) create new endpoint /way/statistics to get info for full statistics (arg - int - calendar days amount: 30 days, 14 days, etc). With all required data: tags statistics, data for chart
- [x] (10 days) add for composite ways logic (it's tricky a little call me when you will start implement it) - each way could have children. We nee just render all of them in the same table

**Comment by tritonJS826** [comment]
done
