### ISSUE TITLE
Delete rendering Day Reports from pdf

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#1255]

**Comment by n144astya** [comment]
Where were the reports displayed? How were they supposed to be unloaded? Need comments

**Comment by kladweb** [comment]
You can create report on your way page:

![Image](https://github.com/user-attachments/assets/d6949ba1-8ff5-4508-9da2-98cef98fc8c1)

**Comment by n144astya** [comment]
done
