### ISSUE TITLE
Header_HomePage:  login button color blends in with the background.

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#1279]
## Steps to reproduce

Open Home page.

## Actual result

< what you get >

The login button is visible and its color is different from the background color.

The login button color blends in with the background.

https://github.com/user-attachments/assets/11f64a6c-3c29-434a-93e4-ccf153113964

**Comment by Ekaterina1994** [comment]
Done

**Comment by n144astya** [comment]
Done
