### ISSUE TITLE
 Empty String for CreateWayPayload.CopiedFromWayUuid in POST Request

### ISSUE THREAD

**Issue by Moon1it** [tritonJS826/masters-way#1300]
## Description

When frontend makes a POST request to the resource "/api/ways", an empty string is being sent for the field CreateWayPayload.CopiedFromWayUuid. If this field is empty, it should not be sent!

**Comment by Ekaterina1994** [comment]
Done. Now when user create new way we send  field CopiedFromWayUuid with value null
