### ISSUE TITLE
"Сервисные работы" modal

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#1311]
show modal when general server healthcheck is fail

**Comment by Ekaterina1994** [comment]
Done

**Comment by n144astya** [comment]
Получаю ошибку:
![сервисные работы](https://github.com/user-attachments/assets/f9babaa3-2af7-4df3-aa9f-2d334a03d378)
 
В фигме вижу другую. Так как пояснений по модалке в задаче нет отправляю на доработку

![image](https://github.com/user-attachments/assets/fac1f8b1-9bf4-4a6e-8fce-e72ac14e655d)

**Comment by n144astya** [comment]
Done
