### ISSUE TITLE
Language: Text of the button ‘Write to connect’ isn’t translated into Russian and Ukrainian languages

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1334]
Preconditions
All ways page opened in a table view

Steps
1.	Open the page of any user
2.	Chose Russian language
3.	Check the text of the button ‘Write to connect’ 
4.	Chose Ukrainian language
5.	Check the text of the button ‘Write to connect’ 

Expected result
Text of the button ‘Write to connect’ is translated into Russian and Ukrainian languages

Actual result
Text of the button ‘Write to connect’ isn’t translated into Russian and Ukrainian languages

![Image](https://github.com/user-attachments/assets/4b080a92-dd37-415b-9b03-90fd09eb0469)
![Image](https://github.com/user-attachments/assets/1647772c-327e-4eab-9429-3a133ec1ddc6)

**Comment by n144astya** [comment]
Done
