### ISSUE TITLE
Fix styles for mobile (modals, labels in statistics, etc)

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#1336]

**Comment by Ekaterina1994** [comment]
![Image](https://github.com/user-attachments/assets/94ad5ae7-da14-479e-9150-22ee9cbfa5df)
![Image](https://github.com/user-attachments/assets/34e5d2e7-9650-4399-aa68-bb919d2e1279)

**Comment by Ekaterina1994** [comment]
Done

**Comment by n144astya** [comment]
Styles done
