### ISSUE TITLE
Can't open some ways

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#1396]
https://mastersway.netlify.app/way/a056a213-2a40-4f81-87e1-65b34f2ed97d

**Comment by Ekaterina1994** [comment]
Can't repeat the bug. Way is opening

![Image](https://github.com/user-attachments/assets/0780cf0a-3ec0-473e-8f3d-4d7160f84e60)

**Comment by evgenia7p** [comment]
Also can't open:
https://mastersway.netlify.app/way/f78ae339-ede2-405d-9908-3806b7b19cab
https://mastersway.netlify.app/way/4bcbcfb2-691b-07cc-f09e-6a256d92ff2a
https://mastersway.netlify.app/way/ae2c6757-fcba-430f-821d-9580ea2682f9

**Comment by evgenia7p** [comment]
Also can't open:
https://mastersway.netlify.app/way/a88a28aa-217b-08d7-3aa0-6bb11fbccf8f



![Image](https://github.com/user-attachments/assets/a7513a9e-fa56-48dd-a468-6050ca70aa39)

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
