### ISSUE TITLE
Make reset db method stable

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#1409]
When resetting the database, the error 'Cached plan must not change result type (SQLSTATE 0A000)' occurs. This happens because the connection is not aware of the deletion of all tables, data types, etc.

**Comment by Moon1it** [comment]
A method to reset the connection cache for PGX Pool has been found - pgxPool.Reset(). This update affected the ResetDB methods in mw-chat and mw-server.
