### ISSUE TITLE
Language: Statistics: Short for word ‘Hour’ isn’t translated into Russian and Ukrainian languages in Overall information section

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1428]
Steps
1. Open any way and check the Overall information in statistics
2. Switch Russian language
3. Switch Ukrainian language

Expected result
Short for word ‘Hour’ is translated into Russian and Ukrainian languages

Actual result
Short for word ‘Hour’ isn’t translated into Russian and Ukrainian languages in Overall information section

![Image](https://github.com/user-attachments/assets/d23f7a8f-d813-4e1b-870a-ae2270dd7220)
![Image](https://github.com/user-attachments/assets/dd5402a7-9a12-45f4-8c30-18cebe162386)

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
