### ISSUE TITLE
Choose what to analyse (SWOT) (specific protocol)

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#1440]
Create file in our docs with SWOT analize

**Comment by tritonJS826** [comment]
done
 https://docs.google.com/document/d/1dBfSUb_eOj3YKZ7EwhfSQuXBKjRJf3GEJudsFt_vT3E/edit#heading=h.imvurxuku77s
https://docs.google.com/spreadsheets/d/1tgHxivpTZxgYl7MDow9fSqnkjWPMRXwnjrCPbBFfFU4/edit?gid=0#gid=0
