### ISSUE TITLE
Way: ‘Make the way private’ option doesn’t work

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#1454]
**Preconditions**
User is authorized. User's way is created and opened

**Steps**
1. Open ‘Way actions’ menu
2. Select ‘Make the way private’ item from the menu
3. Refresh the page

**Actual result**: If you make the way private and refresh the page, it is public again

**Expected result**: ‘Privacy status’ become Private and doesn’t change after page refreshing

https://github.com/user-attachments/assets/741dcf7b-d081-4483-b9d0-0c1f580ff8de

![Image](https://github.com/user-attachments/assets/f3d53859-d68d-4cfc-835c-67ed0e7879f9)

**Comment by Moon1it** [comment]
This problem was solved in last big update (MW-1441/di-refactoring).
