### ISSUE TITLE
Home page: The layout is broken on the RU and UA languages on a real mobile device.

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#1480]
## Steps to reproduce

Open the home page on a mobile device (Samsung) and adjust the zoom so that the entire page fits within the width. Check RU and UA languages.

Opened page before zooming:

![Image](https://github.com/user-attachments/assets/945155e9-26a8-4ec1-966f-f5a4f5c22e58)

After zooming:

![Image](https://github.com/user-attachments/assets/c2a053cd-8d36-4a93-b31e-8d36ce6adac3)

![Image](https://github.com/user-attachments/assets/1d554260-4757-426a-b8af-99c24c55f00d)

**Comment by n144astya** [comment]
IOS 14 pro, 17.6.1

![Image](https://github.com/user-attachments/assets/05fdff23-2313-4eb5-9251-2be1d173c39d)

**Comment by Ekaterina1994** [comment]
Fixed

**Comment by evgenia7p** [comment]
Checked
