### ISSUE TITLE
Day reports: Delete job dialog window spelling mistake.

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#1499]
## Steps to reproduce

1. Log in
2. Open any way, create day report and job done
3. Click delete button to remove the job

Repeat for all languages

## Actual result

Delete job dialog window has text: Are you sure you want to delete the job done ""?

The text has extra space and quotation marks.

## Expected result

Delete job dialog window has text: Are you sure you want to delete the job done?

![Image](https://github.com/user-attachments/assets/dc6459d4-82a3-4956-8057-83a66457c91d)

**Comment by Ekaterina1994** [comment]
@EkaterinaSokolova-V Can't reproduce

![Image](https://github.com/user-attachments/assets/ad3e0ef2-d8dc-4d7d-a910-a2a5cba043d6)

**Comment by Ekaterina1994** [comment]
Если ты имеешь ввиду удаление пустого джоба, то там пустые кавычки потому что джоба пустая

**Comment by EkaterinaSokolova-V** [comment]
@Ekaterina1994 , не догадалась, но вообще странно кавычки смотрятся. Может в случае пустого джоба их не печатать? Или: Вы уверены, что хотите удалить это задание?

**Comment by Ekaterina1994** [comment]
@EkaterinaSokolova-V  Если не печатать кавычки тоже странно. Пустые кавычки показывают что ты удаляешь пустую джобу, а не просто что-то неизвестное удаляешь (в случае отсутсвия кавычек).  В любом случае это не баг. Нужно карточку или на контент мэйкеров переводить, или у Вити в группе уточнить.

**Comment by EkaterinaSokolova-V** [comment]
closed; not a bug
