### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#188]
test cases:

1. Accordion
- [x] accordion option could be opened text visible
- [x] option could be closed (text hidden)
- [x] all options rendered
- [x] all options could be opened
- [x] all options could be opened in multiple modes
- [x] only one option could be opened in multiple mode
2. Checkbox(AKiroi)
- [x] onChange called on click and value not changed if DefaultChecked=false
- [x] onChange called on click and value changes if DefaultChecked=true
- [x] onChange callback should triggered when checkbox is clicked
3. Header(AKiroi)
- [x] alt text visible if source broken
- [x] image visible if source exists
4. Input(AKiroi)
- [x] placeholder visible
- [x] works with input mode text (some symbols are allowed and some not allowed)
- [x] works with input mode email (some symbols are allowed and some not allowed)
- [x] works with input mode number (some symbols allowed and some not allowed)
- [x] could not be used when disabled
- [x] check 'required' logic (does it work correctly)
- [ ] check how to work when props.value and props.onChange exists at the same time
5. Link
- [x] value rendered correctly
- [x] link leads to the right place
6. Modal 
- [x] modal could be opened and closed by clicking on the grey background
- [x] modal could be closed by clicking on the cross
- [x] content rendered
7. Notification
- [x] content rendered
- [x] specify what is foreground and check it works correctly
- [x] specify what is background and check it works correctly
8. Select
- [x] onChange triggered if some option selected
- [x] selected value visible
9. Sidebar
- [x] could be opened and closed by clicking on the grey background
- [x] could be closed by clicking on the cross
- [x] content rendered
10. Table
- [x] table headers rendered in the right way
- [x] data rendered in the right way
11. Title
- [x] text rendered
- [x] appropriate level exists on the page (check semantics)
12. Tooltip
- [x] content rendered
- [x] tooltip is hidden but shown on hover tooltip-trigger
13. Chart
- [ ] content rendered
14. Confirm(Alex89198900)
- [x] #628
15. Dropdown(Alex89198900)
- [x] content rendered
16. Editable text(Alex89198900)
- [ ] content rendered
17. Editable textarea(Alex89198900)
- [ ] content rendered
18. Horizontal container
- [ ] content rendered
19. Icon (test for new dev)
- [ ] content rendered
20. Image
- [ ] content rendered
21. Loader 
- [ ] content rendered
22. Progress bar(AKiroi)
- [ ] content rendered
23. Scrollable block
- [ ] content rendered
24. User card(AKiroi)
- [x] content rendered
23. Vertical container(AKiroi)
- [x] content rendered
23. Way card(AKiroi)
- [x] content rendered

**Comment by Alsandre** [comment]
Hello guys. Today I have started diving into Cypress API. I think I have grasped the basics already. Is it possible for me to tackle this problem? If so are there any specific directions, on how to proceed with the task?

**Comment by tritonJS826** [comment]
Yeah, just create a fork and try to open a new PR into the main branch with a few tests. We will discuss your approach and will decide what to do next, alright?
