### ISSUE TITLE
Prompt component (modal with two buttons)

### ISSUE THREAD

**Issue by Howl404** [tritonJS826/masters-way#322]

**Comment by tritonJS826** [comment]
Do you mean issue 305? if you mark one of them as duplicated and close

**Comment by Howl404** [comment]
@tritonJS826 No, like a template that takes text and callbacks to call on confirm and cancel buttons and creates Modal with it

**Comment by Howl404** [comment]
Or you want to fully replace modal with this?

**Comment by tritonJS826** [comment]
no, it's
