### ISSUE TITLE
Add basic styles (part 2)

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#361]
- [x] Fix dates import/export
- [x] add some space between interactive elements
- [x] remove horizontal scroll on hover any item
- [x] align text in tables (favorites, check other)
- [x] fast creating new way lead to missing some of them in the userPage [????]
- [x] align "Total" in dayReports table in jobs done
- [x] add redirect on create new way
- [x] align tooltip with icons (mentors block, check other)
- [x] I'm not a mentor for this way https://mastersway.netlify.app/way/Ez0jt0qOwGmn0Wsj4ju4, but it is in my mentoring table (super often regression, root cause should be fixed)
- [x] Align data in table cells mobile view (new way, short columns)
- [x] Overflow for tables (show tooltips) [???]
- [x] Get rid of accorfions (eye buttons with local storage) [6h]
- [x] check dates in all tables on mobile [3h]
- [x] check color contrast [1h] (talk with anna)
- [x] fix scroll appears on hover favorites because of tooltip [1h] (the same for comments "add" button)
- [x] jobDone, plans: aling trash icon, number [3h],
- [x] move summary in the cells to the bottom [1h]
- [x] align checkbox sizes in table [1h]
- [x] add appropriate access rules to checkbox [1h]
- [x] move check box on the line with the name, add tooltip coming soon, remove checkbox from the comments [1h]
- [x] add button - light theme - plus not visible (in Fiefox) [1h]
- [x] check tables heading in firefox (they are disappeared for me) [2h]
- [x] wide md images broke mobile layout [2h]
- [x] add gap between checkbox and description in metrics block [1h]
- [x] strange width balance in columns
- [x] wrong commentator (https://mastersway.netlify.app/way/Ez0jt0qOwGmn0Wsj4ju4) (it was me but now it is Dayana) [3h] (add migration like "formerMentors")
- [x] remove env variables from the repo
- [x] ways page: align status and waysOwner
- [x] inputs width sometimes too short, I think 3 symbols should be visible
- [x] https://mastersway.netlify.app/way/9kRSzgPVux6UYIHnhqlh cell it too large if some word could not be wrapped
- [x] can't open some ways (user with uuid is not defined (ekaterinas way))
- [x] align trash icons in mentors
- [x] Error after pressing vreate new day report
- [x] as a mentor I can't change estimations in plans for tomorrow. But I should be able
- [x] please, mark my way about read book as completed in the firebase
- [x] replase visibility selects on svg icons (or checkboxes)
- [x]  align trash icon (remove mentor)
- [x] fix code tag in md in md custom elemets
- [x] I cant open Dayana's main way (page 404 appeared)

**Comment by Ekaterina1994** [comment]
Done
