### ISSUE TITLE
Refactor WayColumns.tsx

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#371]
- [x] Too much wrappers in cells
- [x] Simplify jsx of cells (example, lines map function for render list of jobsFone)
- [x] simplify all structure like row.origin.comments / plans etc

**Comment by Ekaterina1994** [comment]
Was refactoring of dayreports table. If it's possible need to check styles for table with dayReports on WayPage

**Comment by pp2amd6** [comment]
Closed without stiles testing because Way page not re-designed yet
