### ISSUE TITLE
Improve labels experience

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#490]
- [ ] add ability to update  label's name
- [x] prepare models (make migrations)
- [x] add tag description
- [x] add tag color picker

**Comment by Ekaterina1994** [comment]
@tritonJS826 Do you mean  possibility to update labels name because I remember that we decided don't allow update skills and wayTag names?

**Comment by tritonJS826** [comment]
Yeah, right, labels

**Comment by Ekaterina1994** [comment]
Done
