### ISSUE TITLE
Fix scroll bug

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#591]
Bug registered by user:
1) при нажатии кнопки "add job" происходит прокручивание страницы наверх. при повторном нажатии - скролла нет.
2) больше UX, чем баг: при наведении на область со временем выполнения задания, курсор бесконечно переключается между cursor и text состояниями. Причем если нажимать прямо на цифру 0, то активации состояния ввода текста не происходит. А вот если нажать чуть левее, где курсор в состоянии default (и ничто не указывает на то, что туда можно нажать), то активация поля ввода происходит

**Comment by Ekaterina1994** [comment]
1. Not a bug. Scrolling added because after creating job statistic block creates too
2. Fixed

**Comment by tritonJS826** [comment]
done
