### ISSUE TITLE
Add collection card

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#597]
- [x] add wayCollectino card
- [x] add menu with actions (rename, delete)
- [x] check text according #850

**Comment by EkaterinaSokolova-V** [comment]
@Ekaterina1994 , in the case of long collection titles, is displaying the collection card title in this format expected?

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/661c1f86-9f66-4a18-8c90-ae3e0894d8df)

**Comment by Ekaterina1994** [comment]
![Image](https://github.com/tritonJS826/masters-way/assets/57002521/b326eeea-87a6-4ab7-ac0b-bacf2a232866)
![Image](https://github.com/tritonJS826/masters-way/assets/57002521/093352ca-e9e0-466e-9bdb-67d8d3f80740)

**Comment by Ekaterina1994** [comment]
@EkaterinaSokolova-V  Fixed, thanks
