### ISSUE TITLE
Application not save empty email on user page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#672]
When user set empty value for email field on user page (/user/<user-id>), previous value will be shown

## Steps
1. Go to user page
2. Double click on email field and clear page
3. Click on any part of page, "*Empty markdown! Double click on me!*" placeholder for field will be [presented](https://i.imgur.com/OWWzcu7.png)
4. Refresh page
5. Previous (non-empty) value for field [presented](https://i.imgur.com/OWWzcu7.png)

## Expected result
Empty value shows in email field

## Actual result
Non-empty value shows in email field

## Additional info
Bug reproduces on [DEV env](https://mastersway-dev.netlify.app/)
Bug **NOT** reproduces on [DEMO env](https://mastersway.netlify.app/)

Google Chrome, Version 123.0.6312.123 (Official Build) (64-bit)

**Comment by tritonJS826** [comment]
Ok, I think we should forbid to change email. In progress

**Comment by tritonJS826** [comment]
We blocked ability to change emails for users for now.

**Comment by EkaterinaSokolova-V** [comment]
done
