### ISSUE TITLE
Tag field has strange blur in tag adding modal

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#674]
Strange blur shown for tag (skill / job tag / way tag) field in tag adding modal.
This behavior applied only when field have focus. Blur is gone when field lose focus.

## Steps
1. Open user page (/user/<user-id>)
2. [Click on "+" under email field](https://i.imgur.com/v1MWTgW.png)
3. [Field blur is applied because it has focus](https://i.imgur.com/dTDmujo.png) (font blurred)
4. [Change focus to Cancel button for example and tag field lose focus and presented normally](https://i.imgur.com/PCQO5Pg.png)

Same behavior applied for [way tag](https://i.imgur.com/T3GzgI5.png) on way page and for [job tag](https://i.imgur.com/rd3pVHz.png) on way page

## Actual result
Tag field shown with blur

## Expected result
Tag field shown normally

## Additional info
Reproduced on Demo and Dev

Google Chrome, Version 123.0.6312.123 (Official Build) (64-bit)

**Comment by pp2amd6** [comment]
@tritonJS826 maybe add this fix as part of the task #490?

**Comment by tritonJS826** [comment]
minor, cant reproduce

**Comment by pp2amd6** [comment]
> minor, cant reproduce

Confirm. The error no longer reproduces
