### ISSUE TITLE
Response error while trying apply as Mentor on way page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#676]
## Steps
1. Open other user way
2. Press "Apply as Mentor" button
3. Response error appeared
![image](https://github.com/tritonJS826/masters-way/assets/4976837/19e9fbd7-6714-4edc-80ca-5c0d8fc0d115)

## Actual result
Response error appeared

## Expected result
Application to become a mentor has been sent

**Comment by Ekaterina1994** [comment]
Done in 696 PR
