### ISSUE TITLE
User's Way: the actual number of ways does not match that indicated on the Mentoring Collection Button

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#679]
**Steps:**

1. Open https://mastersway-dev.netlify.app/user/db9b7631-6729-5807-13b7-4d1f8dbde568 user presonal area (Anastasiya Danilava).
2. Click "mentoring" collection button.

**Expected result:** 
Three ways are displayed as indicated on the "mentoring" collection button.

**Actual result:**
Two paths and "Way with uuid "a88a28aa-217b-08d7-3aa0-6bb11fbccf8f" is was removed or hidden. Remove it from the collection?" message are displayed.

If click this message, a pop-up window will appear with the text:
"Are you sure you want the way "a88a28aa-217b-08d7-3aa0-6bb11fbccf8f" from the collection?"
If click "Ok" on this window, the notification appears: "Ups, Error: User is not defined".

**Enviroment:** 
Windows 11, Chrome Version 123.0.6312.123 (Official Build) (64-bit)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/8d225460-bdc1-4540-9296-54af7b485b02)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/d0d4c166-e8eb-4b79-90a8-fa60ed0c0cc2)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/8eddd218-3573-43c9-9440-c5ce1a414e51)

**Comment by tritonJS826** [comment]
This is normal behavior. If the way become private or was removed in users collections we don't remove it, to notificate subscribers somehow. We should improve view for this button

**Comment by tritonJS826** [comment]
realted to #480

**Comment by EkaterinaSokolova-V** [comment]
In this case I don't login and just open other users ways. It seems to me that there should be a view mode.

**Comment by Ekaterina1994** [comment]
Was fixed after migration. Can't to reproduce

**Comment by EkaterinaSokolova-V** [comment]
fixed
