### ISSUE TITLE
Mentoring collection button: the actual number of mentoring ways does not match that indicated on All users page

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#680]
**Steps:**
1. Open All users page: https://mastersway-dev.netlify.app/users
2. Find 'Viktar Veratsennikau'. In accordance with this table, this user has 34 ways.
3. Click this user name to go his personal area page or go to: https://mastersway-dev.netlify.app/user/ec3e7405-02d2-fdd4-e0ac-f9b1e2082f76
4. Check the number of mentoring ways of this user.

**Expected result:**
The number of ways of this user is 34 (as on the All users page).

**Actual result:**
The number of displayed ways 33.

**Enviroment:**
Windows 11, Chrome Version 123.0.6312.123 (Official Build) (64-bit)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/8c055a24-7211-4eb3-8091-1b94503d2a88)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/a9288815-d3bc-431c-a775-53b0a421559c)

**Comment by tritonJS826** [comment]
looks like it related to private ways. Shuold be checked on the back

**Comment by tritonJS826** [comment]
after investigation looks like it is related to  broken data on the demo (bc of firebase nature). Each case should be registered and fixed manuaklly

**Comment by tritonJS826** [comment]
fixed in #695
