### ISSUE TITLE
The placeholder for the "Goal" section is shown on the mentee`s way page.

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#683]
When user open way page of mentee he can see placeholder for Goal section if field not filled by mentee.

## Preconditions
As mentee clear Goal field in Goal section.

## Steps to reproduce
1. Open mentee`s way page
2. Look at Goal section.
3. User see placeholder for Goal field in Goal section

## Actual result
User see placeholder for Goal field in Goal section
![image](https://github.com/tritonJS826/masters-way/assets/4976837/cce011c9-d3a7-47a6-a148-cdf698abf767)

## Expected result
User shouldn`t see placeholder for empty Goal field in Goal section
![image](https://github.com/tritonJS826/masters-way/assets/4976837/72a06cee-0a63-491c-beb1-af5f5d8d4240)

**Comment by EkaterinaSokolova-V** [comment]
fixed
