### ISSUE TITLE
Add ability to add/remove way to composite way

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#693]

**Comment by tritonJS826** [comment]
Done

**Comment by tritonJS826** [comment]
Should be implemented on the front

**Comment by tritonJS826** [comment]
* add links to ways to jobs, plans etc
* extend description block (list of ways with owners)

**Comment by Ekaterina1994** [comment]
Done

**Comment by Ekaterina1994** [comment]
@EkaterinaSokolova-V 

https://github.com/tritonJS826/masters-way/assets/57002521/627a6ef9-6dc5-4af3-938c-ccc5dfebd04c

**Comment by EkaterinaSokolova-V** [comment]
Done
