### ISSUE TITLE
All users: the actual number of favorite way does not math that indicated on user's way

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#695]
**Steps:**

1. Open All users page: https://mastersway-dev.netlify.app/users
2. Find 'Гончарук Никита (IT-Academy)'. In accordance with this table, this user has 0 favorite ways.
3. Click this user name to go his personal area page or go to: https://mastersway-dev.netlify.app/user/c9b8aabc-72e9-fb13-8c5d-fb7b03097d60
4. Check the number of favorite ways of this user.

**Expected result:**
The number of ways of this user is 0 (as on the All users page).

**Actual result:**
The number of displayed ways 2.

![image](https://github.com/tritonJS826/masters-way/assets/142949669/7d596996-1671-45f4-8f51-de28ce766ae5)
 
![image](https://github.com/tritonJS826/masters-way/assets/142949669/bc712544-afb5-4bb1-b59e-0936bf489d0c)

**Comment by n144astya** [comment]
same error only on own way. Page https://mastersway-dev.netlify.app/user/db9b7631-6729-5807-13b7-4d1f8dbde568  and 
https://mastersway-dev.netlify.app/users Find (Anastasia Danilava)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/686f4488-d333-484b-9771-e0bc4481bb31)
![image](https://github.com/tritonJS826/masters-way/assets/142949669/9f514a47-dec0-4de5-98a0-d13f3c6ae760)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/0451a57b-ac91-4f5a-9e1b-568782bfcb35)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/b5e09d94-cd72-49eb-a422-5f1884018e93)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/541f2772-f17b-4a12-80fa-57797c11478e)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/b520b819-0217-4951-b7cb-9c6d12fe4cae)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/b6d28872-3438-4b4c-99ac-c59d33a9911b)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/18e0762b-5493-4d2e-aae6-5acb06471d36)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/3ecd1277-ca36-4a54-aa36-8164b7968203)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/5b6b9555-29ca-46f6-ae6b-4bed00dd1b39)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/3333567d-bd24-488c-9099-fce022b246c7)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/1b7f986e-4eb6-4685-b146-2578417bbd57)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/62751f99-c9e2-45ba-83e7-1a6a9003d193)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/3394312f-6e6d-416b-a0a6-507d6cb9b404)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/d45a9808-82cc-4bbf-8671-39385980e93e)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/a44315a7-bf7a-4c8c-aeb7-d8fbbf2ca3af)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/5ef304f5-6140-41b7-b8ce-c643d1dbbad8)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/f35e3e1d-8645-47eb-89a9-d054b709f5ec)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/0c8b3d26-c345-4be1-8db2-83570b6fc1fa)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/8a692f7b-6596-45fc-a9b8-83b0639feb33)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/efb10bec-6c43-4d95-b215-0673aa3611ff)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/10a11663-c606-4d34-a05a-5db52d068152)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/1128acb3-d6d2-4bbd-83e5-cce6c5831162)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/dfd68bfb-f55b-44f1-9136-08727fc6b7a4)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/7255ab98-d565-4945-87aa-39f0c69dbed0)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/8999d9cd-30f4-433e-b59f-37c9fa44ea9d)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/e74ae6a2-eacf-4d17-9d68-b19756b652c1)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/e9624edb-19d5-40ea-81de-f1cd5ee4fb3a)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/2583936a-965a-4e9b-838b-f94503e018d9)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/19dbd9af-af0e-4e5c-8c1b-1e5478e93a98)

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/d02d241b-cfec-43f7-b217-360789b942ea)

![image](https://github.com/tritonJS826/masters-way/assets/142949669/ff32af19-43e1-466c-a2c3-73a23b3b9a67)

**Comment by tritonJS826** [comment]
Fixed for favorites
Looks like there are a problem with some mentoring ways bc of broken data on firebase

**Comment by tritonJS826** [comment]
we should remove all pseudocollections like own, mentoring, favorite from the database

**Comment by tritonJS826** [comment]
fixed

**Comment by tritonJS826** [comment]
we should remove all pseudocollections like own, mentoring, favorite from the database

**Comment by pp2amd6** [comment]
> Please reassign it on me and move to dev todo column after the approve that everything currently ok with the logic related to own, mentoring, favorite collections

Done

**Comment by tritonJS826** [comment]
We need to 
* remove types on the back
* remove default collections on create way
* remove filter by types from the back

**Comment by n144astya** [comment]
Done

**Comment by tritonJS826** [comment]
Done. Basic recheck for basic collections required
