### ISSUE TITLE
add to mentor logic broken

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#696]
не понимаю что тут происходит в плане запросов, выглядит как ничего  

mw-webapp/src/logic/wayPage/MentorRequestsSection.tsx
problem in the requests in the consts: addMentorToWay, removeUserFromMentorRequests

должно быть добавление в коллекцию mentoring для специфического юзера + в таблицу mentor_users_ways

**Comment by pp2amd6** [comment]
Это один и тот же баг с [#676](https://github.com/tritonJS826/masters-way/issues/676)?
