### ISSUE TITLE
UX/UI Header_TooltipDarkThemeIcon: not enough contrast, login button and tooltip overlap each other and merge

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#697]
**Steps:** 
1. Open any page, for example: https://mastersway-dev.netlify.app/ways
2. Light theme selected.
3. Hover over the theme icon.

**Expected result:**
"Switch to dark theme" tooltip appears next to Theme icon. All other header elements are visible.

**Actual result:**
Login button and tooltip overlap each other and merge. Both has the same color, there is no any contrast border of the tooltip.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/5a53f720-f744-44f5-9848-9e61ad9638fb)

Please compare with a similar situation but for a dark theme:

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/b7636058-3691-46f5-90e5-2ca8bfbb1fe2)

**Enviroment:**
Windows 11, Chrome Version 123.0.6312.123 (Official Build) (64-bit)

**Comment by EkaterinaSokolova-V** [comment]
related to: https://github.com/users/tritonJS826/projects/4/views/1?pane=issue&itemId=60691042

**Comment by vikpak89** [comment]
![Image](https://github.com/tritonJS826/masters-way/assets/167992048/fafa4183-a2c9-4054-8f76-72710cd5a40b)

https://www.figma.com/file/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?type=design&node-id=1996%3A44462&mode=design&t=ZlQHtGSX4QsEkWa3-1

**Comment by Ekaterina1994** [comment]
Need to fix variable = text is not border )

![Image](https://github.com/tritonJS826/masters-way/assets/57002521/710ff658-9bb0-4324-9372-ea6a2facb625)

**Comment by Ekaterina1994** [comment]
Do we need updated styles for ttoltip according design ( on image)?  Right now tooltips in demo is nor equal to the figma imiage. Or it will be other task?

**Comment by EkaterinaSokolova-V** [comment]
done
