### ISSUE TITLE
UserWay_CardView: way mentors are not displayed in way card

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#699]
**Steps:**
1. Open https://mastersway-dev.netlify.app/user/ec3e7405-02d2-fdd4-e0ac-f9b1e2082f76
2. Click Card view icon.
3. Click "mentoring" collection button.
4. Check mentor name for any way card.

**Expected result:**
The way cards display the name of the mentor in this case of Viktar Veratsennikau.

**Actual result:**
The way cards do NOT display the name of the mentor in this case of Viktar Veratsennikau. There is "No mentors yet" text.

**Enviroment:**
Windows 11, Chrome Version 123.0.6312.123 (Official Build) (64-bit)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/163e2f31-69f0-496f-871e-dabb83a90b99)

**Comment by tritonJS826** [comment]
done
