### ISSUE TITLE
"Add to favorites" button is not displayed correctly when dark theme used

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#703]
"Add to favorites" button is not displayed correctly on way page when dark theme used.

## Steps
1. Open any way :)

## Actual result
The button has a dark font color
![Image](https://github.com/tritonJS826/masters-way/assets/4976837/b354aa89-2598-460a-8669-8e896c48f2d2)

## Expected result
The button has a light font color
![Image](https://github.com/tritonJS826/masters-way/assets/4976837/8a4fa3f1-f7a0-4f51-8430-da3f2e17ceec)

**Comment by tritonJS826** [comment]
Done

**Comment by pp2amd6** [comment]
> Done

Almost XD https://github.com/tritonJS826/masters-way/issues/711
