### ISSUE TITLE
the value on the "language change" button in the upper right corner does not change.

### ISSUE THREAD

**Issue by temamas03** [tritonJS826/masters-way#707]
When changing the language on the "language change" button in the left sidebar, the value of the selected language on the "language change"  button in the upper right corner does not change.
**STEPS TO REPRODUCE**

1. Open https://mastersway-dev.netlify.app/aboutProject
2. Open "About our project" page
3. Click on the menu button at the right corner
4. Click on 'Switch language' button at the left sidebar
5. Choose any language besides default EN (UA for example)
6. Look at the "language change" button in the upper right corner

**ACTUAL RESULT**

![Image](https://github.com/tritonJS826/masters-way/assets/166903361/a74418e4-216b-4b58-958a-cd7e4f8fe738)

**Comment by tritonJS826** [comment]
done

**Comment by EkaterinaSokolova-V** [comment]
Fixed

**Comment by EkaterinaSokolova-V** [comment]
Fixed

**Comment by EkaterinaSokolova-V** [comment]
Fixed
