### ISSUE TITLE
Login button

### ISSUE THREAD

**Issue by vdruda** [tritonJS826/masters-way#710]
Steps:
1.Click on the button Login
2.Close window with Autorisation
3.Click on the button Login again

Video: https://drive.google.com/file/d/1sgvBC5AfN-VLvXHHFj0HztoWXvlRsSxs/view?usp=drive_link

**Comment by vdruda** [comment]
Steps:
1.Click on the button Login
2.Close window with Autorisation
3.Click on the button Login again

Video: https://drive.google.com/file/d/1sgvBC5AfN-VLvXHHFj0HztoWXvlRsSxs/view?usp=drive_link

**Comment by Ekaterina1994** [comment]
Connected with issue #435

**Comment by tritonJS826** [comment]
Duplicate of #435

**Comment by pp2amd6** [comment]
Closed because https://github.com/tritonJS826/masters-way/issues/435 moved to backlog
