### ISSUE TITLE
"Add to favorites" button shown for non logged user

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#718]
"Add to favorites" button shown for non logged user on way page

## Steps
1. Open any way as non logged user (in private browser mode for example)
2. Look at top right corner of Way info section

## Actual result
"Add to favorites" button shown for non logged user
![Image](https://github.com/tritonJS826/masters-way/assets/4976837/2d062f8c-386f-4062-aa90-02e01306488f)

## Expected result
"Add to favorites" button not shown for non logged user
![Image](https://github.com/tritonJS826/masters-way/assets/4976837/7e48817f-2ab0-4e1e-ad35-8457f502a327)

**Comment by tritonJS826** [comment]
I think it is ok to give to user aboity to see amount of starts here. The buttun shoudn't be clickable if user is not logged in

**Comment by pp2amd6** [comment]
> I think it is ok to give to user aboity to see amount of starts here. The buttun shoudn't be clickable if user is not logged in

Then maybe prohibit pressing the button and not show a tooltip?
The tooltip indicates functionality that is not available for a non-logged in user and will confuse the user

![image](https://github.com/tritonJS826/masters-way/assets/4976837/3962f916-f98b-4450-b626-549c4af7ec16)

**Comment by pp2amd6** [comment]
@tritonJS826

**Comment by tritonJS826** [comment]
Yeah, good point, thanks!

**Comment by Ekaterina1994** [comment]
Done

**Comment by EkaterinaSokolova-V** [comment]
Please look at the "Likes count" is still clickable:


https://github.com/tritonJS826/masters-way/assets/115548501/bca9543b-31b2-4a8b-aeec-27ed5e78c3e2

**Comment by EkaterinaSokolova-V** [comment]
fixed
