### ISSUE TITLE
Way Metric marked as incomplete when user cancel operation of Metric incompleting

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#721]
Way Metric marked as incomplete when user cancel operation of Metric incompletion.
In reality, the status of the metric does not change.
Metric showing as complete after page reload.

## Precondition

1. The user is already authorized in the application using his Google account
2. The user has a mentee
3. Mentee way page already opened
4. Mentee way already have at least one metric marked as **completed**

## Steps

1. Click on the checkbox to the left of the metric name
2. Click on "Cancel" button or popup window cross
![Image](https://github.com/tritonJS826/masters-way/assets/4976837/2fd54c86-46a1-4450-b85e-716bfde6e7ea)

3. Metric shown as incomplete
4. Reload page
5. Metric shown correctly as complete 

## Actual result
Way Metric marked as incomplete when user cancel operation of Metric incompletion

## Expected result
Way Metric status not changed to incomplete

https://github.com/tritonJS826/masters-way/assets/4976837/d8c38267-f641-4be7-a695-4d36cfe84848

**Comment by Ekaterina1994** [comment]
Maybe duplicate with #662
