### ISSUE TITLE
The click outside of "Add tag" button call new tag popup

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#723]
The click outside of "Add tag" button call new tag popup

## Precondition
1. The user is already authorized in the application using his Google account
2. The user has a mentee
3. Mentee way page already opened

## Steps
1. Click on "Adjust job tags" button
2. Click outside of "Add tag"  button
3. Popup window for entering tag name is shown
![Image](https://github.com/tritonJS826/masters-way/assets/4976837/6d7d02b6-ad7b-4b86-9bd9-747da5770477)

## Actual result
The click outside of "Add tag" call create new tag popup

## Expected result
The click outside of "Add tag" does not cause any reaction

**Comment by tritonJS826** [comment]
https://github.com/tritonJS826/masters-way/assets/56690686/d968b20a-38ca-4f0a-b012-46b3f474d956
