### ISSUE TITLE
Mentor-menti: the mentor has access to edit the job done of menti

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#724]
**Steps:**
1. Mentor user is loged in.
2. Go to "mentoring" collection and open a mentoring way.
3. Click "Add job" in Jobs done report and create new job or delete existing one.

**Expected result:**
Mentor is NOT able to edit Jobs done of his menti.

**Actual result:**
Mentor is able to edit Jobs done of his menti.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/52b24dae-eb38-4503-bee0-778c32077f7e)

**Comment by Ekaterina1994** [comment]
Есть потенциальная проблема, если убирать данную возможность, то нужно убирать и возможность ментором ставить чекбокс в планах. Однако, это будет мешать ментору проверять студента. Считаю, что ментор по договоренности может помогать студенту, особенно первое время, писать джобы, чтобы показать как правильно заполнять отчеты. ПОэтому лучше обсудить еще раз с @tritonJS826 . Если ментор не хочет заполнять джобы, то его никто не  сможет обязать, но при этом возможности сотрудничества расширяются.

**Comment by tritonJS826** [comment]
Давайте пока договоримся что ментор все-таки может джобы добавлять, наверно в самом деле в начале показать как что где писать для ментора будет удобнее, чем в комментах ошибки исправлять

**Comment by EkaterinaSokolova-V** [comment]
archived
