### ISSUE TITLE
Brackets symbols doubling after pasting text from Google Sheets that contains two lines when brackets are at the start of sentence in reports section of my way page

### ISSUE THREAD

**Issue by nick1gon** [tritonJS826/masters-way#725]
After pasting text from Google Sheets that contains two or more lines (lines that was produced by user manually (e.g. pressing Enter button)) brackets symbols at the beginning of the sentence in reports section of my way page brackets symbols double.

Actual result: brackets symbols at the start of the sentence doubling and text format changed (instead of two lines there is single line).
Expected Result: valid number of brackets symbols in the each line of the text pasted by user and valid number of lines in this text.

Steps:

1. Authorize
2. Open any of your ways
3. Paste "1"
              "a" (two line of text with brackets symbols)

![Bug report 1](https://github.com/tritonJS826/masters-way/assets/156530297/7b5719b4-8ce0-4e33-91aa-5a29c44186a7)

**Comment by Ekaterina1994** [comment]
Can't repeat bug. Need more details

https://github.com/tritonJS826/masters-way/assets/57002521/338d7bba-d685-48c6-9842-5abaa12e2fcd

**Comment by n144astya** [comment]
Fixed. Closed
