### ISSUE TITLE
User's ways: incorrect tooltip text for "Delete job" button

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#728]
"Delete job" button have incorrect text.

## Precondition
1. Create day report
2. Create at least one job

## Steps
1. Hover on "Delete job" button (recycle bin icon)

## Actual result
Tooltip with text "Delete jobDone" presented
![image](https://github.com/tritonJS826/masters-way/assets/4976837/ab088e52-4da9-4d94-9846-05cb2728d50a)

## Expected result
Tooltip with text "Delete job" presented
![image](https://github.com/tritonJS826/masters-way/assets/4976837/227118a2-fa1c-46a1-bba8-b05c26fc5baa)

**Comment by Ekaterina1994** [comment]
@tritonJS826  Need to think about naming for JobDones. If we will call it jobDone then it's not a bug, if in tooltip we will change jobDone into job then maybe Column need rename too.

**Comment by tritonJS826** [comment]
Changed on "delete job"

**Comment by EkaterinaSokolova-V** [comment]
done
