### ISSUE TITLE
[Suggestion] Don't show progress for Ways without Metrics on the user page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#735]
Don't show progress for Ways without Metrics on the user page because it doesn't make any sense.
For Ways that have Metrics, displaying information by Metrics is convenient and justified

## Actual
![image](https://github.com/tritonJS826/masters-way/assets/4976837/48d96140-d441-4f73-8db7-b1389da40a4c)

## Expected
![image](https://github.com/tritonJS826/masters-way/assets/4976837/e0897a57-f2f7-47d7-a9fd-5562bb5e7903)

**Comment by tritonJS826** [comment]
It will bring unconsistent view in cards, let's skip for now. Also it could hard for users to understand why does some ways don't have  a progress bar in the table. For now don't see any benefits from user perspective, let's discuss it if i am wrong.

**Comment by pp2amd6** [comment]
> Also it could hard for users to understand why does some ways don't have a progress bar in the table

For less experienced users...maybe. Ok, agree with you.
