### ISSUE TITLE
way description: "Repeat the way" function not work correctly

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#736]
"Repeat the way" function not work correctly. New Way does not contain Metrics from origin Way and not shown in Ways list on user page who copy Way.

## Preconditions
1. Create Way with some data
![image](https://github.com/tritonJS826/masters-way/assets/4976837/9866f282-2dd0-4ab1-b8a1-64ec101d2f43)

## Steps
1. Click on the "[Way actions](https://i.imgur.com/VTRwC2P.png)" button which located in the "Way info" section
2. Click on the "Repeat the way" menu item

## Actual result
The new Way page has been loaded. There is no original Way data in the copied Way.
![image](https://github.com/tritonJS826/masters-way/assets/4976837/8a9a7f68-1395-4461-99f4-78a85d68249d)

Also new Way not showed in Ways list on user page who copy Way
![image](https://github.com/tritonJS826/masters-way/assets/4976837/35fa7aa6-c12c-4b5c-a935-7244de116365)

But new Way shown in "All ways" page with user who copy Way as Owner
![image](https://github.com/tritonJS826/masters-way/assets/4976837/a5e03227-3cb2-4e18-9b4f-0045f9b79042)

## Expected result
The Way contain data from origin Way (tags, metrics, name?)
The Way shown in Ways list on user page who copy Way

**Comment by tritonJS826** [comment]
done

**Comment by Ekaterina1994** [comment]
@pp2amd6 Can't reproduce this bug, maybe was fixed

**Comment by pp2amd6** [comment]
Closed. The bug no longer reproduces
