### ISSUE TITLE
User Ways: after adding new report, the way status does not change from 'Abandoned' to 'In Progress'/'Last update' does not update

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#738]
## Description

After adding new report, the way status does not change from 'Abandoned' to 'In Progress' and 'Last update' is not updated.

## Preconditions

User has Abandoned way.

## Steps to reproduce

1. Login.
2. Open Abandoned way and add new day report.
3. Go to user personal area and set table view mode.
4. Check this way Status in the table and 'Last update' date.

## Actual result
'Last update' does not update.
The Way Status is 'Abandoned'.

## Expected result
'Last update' is updated according to the latest report date.
The Way Status is 'In Progress'.

## Test data
User way: https://mastersway.netlify.app/way/91fb4846-d47f-9709-74e0-5d6afb03832f

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/c759f6fc-dd25-4a48-9908-307e910567ec)

**Comment by Ekaterina1994** [comment]
Connect with #792
