### ISSUE TITLE
UX/UI_User's ways_card view mode: no contrast when displaying info tooltips for way cards

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#743]
## Steps to reproduce

1. Open any personal user area, for example: https://mastersway.netlify.app/user/707db81c-4433-a6d3-cabd-1a9270ada8b6
2. Click card view icon.
3. Hover cursor over all available data (title, goal, reports, likes) on a way card.

## Actual result

The color of the tooltips matches the card color, so they merge together, there is no contrast.

## Expected result

Displayed tooltips are well readable and do not merge with the background colors.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/55f43750-6537-4f7b-bbfc-5fe7e5d1f7ef)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/67cdb860-3b58-42b2-8ecc-dde003ee4349)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/0e0cea07-9b6f-40fe-b708-32de4cf65a05)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/820de6f0-22f6-42f7-90cd-d5532963c4d2)

**Comment by Ekaterina1994** [comment]
Connect with #697

**Comment by EkaterinaSokolova-V** [comment]
done
