### ISSUE TITLE
Way description: The way does not appear in the specified collection when click on "Add to <collection name>" menu item.

### ISSUE THREAD

**Issue by snyajanka** [tritonJS826/masters-way#746]
## Description

The way does not appear in the specified collection when click on "Add to <collection name>" menu item.

## Preconditions

1. There is at least one way for the logged in user.
2. Open this way page.
3. Collection is created.

## Steps to reproduce

1. Open Way action dropdown menu.
2. Click on "Add to <collection name>" menu item

## Actual result
When you click on the menu item “Add to <collection name>”, a message appears highlighted with a red frame.
<img width="938" alt="Bug" src="https://github.com/tritonJS826/masters-way/assets/166917057/3bdbaf4b-6aee-4a09-a9ff-5ab52356427f">

When we go to our main page, we see that the way has not been added to the collection.
<img width="697" alt="Bug2" src="https://github.com/tritonJS826/masters-way/assets/166917057/2cbe3c59-1a59-4d79-b82f-77dae39d3c20">

## Expected result

The way adds to the specified collection.

## Additional context
When we click on the browser icon 'Refresh this page', the path is displayed in the collection.
<img width="670" alt="Bug3" src="https://github.com/tritonJS826/masters-way/assets/166917057/1824d5b4-677f-4d7e-bab6-95f200f3deb2">

**Comment by Ekaterina1994** [comment]
Can't repeat bug in my account. Need more details

**Comment by Ekaterina1994** [comment]
Fixed
