### ISSUE TITLE
UX/UI_Statistics: most of the way page is blank when the hide statistics option is selected

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#748]
## Steps to reproduce

1. Open any way page.
2. Hide a Statistic block clicking eye icon.

## Actual result

Way statistics are hidden.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/2ed7b8c9-fd54-4126-8706-eba3f67a7861)

Perhaps the option to hide statistics is not needed for the desktop version.

**Comment by tritonJS826** [comment]
Is it ok to just hide button for hiding statistics block for desktop resolutions?

**Comment by tritonJS826** [comment]
Agreed to hide eye button

**Comment by vikpak89** [comment]
@tritonJS826  there is no need to hide statistics on the web version, we need to remove the eye icon

**Comment by Ekaterina1994** [comment]
Done

**Comment by EkaterinaSokolova-V** [comment]
Done
