### ISSUE TITLE
Statistic: labels statistic status bars are not completely colored (part of the bar is left blank)

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#749]
## Steps to reproduce

1. Open any way, for example: https://mastersway.netlify.app/way/4193c283-53dd-1f28-34e2-36e003bf0eb7
2. Click 'Show all statistic' button or you can skip this step.

## Actual result

Labels statistic status bars are not colored over the entire length depending on the labels data. The right side of the bars is not colored over.

## Expected result

Labels statistic status bars are colored over the entire length depending on the labels data.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/d887d347-00e6-4389-ab61-80623a072020)

**Comment by Ekaterina1994** [comment]
It's a chart library problem.

**Comment by evgenia7p** [comment]
Checked
