### ISSUE TITLE
UX/UI_Way metric progress bar: the progress bar is not visible and has insufficient contrast with no one completed metric

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#750]
## Steps to reproduce

1. Open any way with no one completed metric, for example: https://mastersway.netlify.app/way/4193c283-53dd-1f28-34e2-36e003bf0eb7
2. Check way metric progress bar in 'Goal' section.

## Actual result

The progress bar is not visible.

## Expected result

The progress bar is visible.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/251922e9-7d6a-43c3-a519-38c0d83543ce)

The color of the bar is the same as the background:
![Image](https://github.com/tritonJS826/masters-way/assets/115548501/e953134e-9d3a-4e02-aa00-6f9f988ded56)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/08cab3ea-d943-41cc-a40a-afcc45064356)

Display of Way metric progress bar with one completed metric.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/958fb366-1fb5-4aae-812d-6219c5251169)

**Comment by Ekaterina1994** [comment]
Done

**Comment by EkaterinaSokolova-V** [comment]
Fixed
