### ISSUE TITLE
All ways page_table view mode: some ways with progress '0%_____0/0' has 'Completed' status, others - 'In progress'

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#752]
## Steps to reproduce

1. Open All ways page: https://mastersway.netlify.app/ways
2. Switch to table view mode.
3. Compare list of 'Completed' ways with 'In progress'.

## Actual result

Some ways with progress '0%_____0/0' or '0%_____0/N' (N > 0) have 'Completed' status.

## Expected result

All ways with progress '0%_____0/0' or '0%_____0/N' (N > 0) have 'In progress' status.

## Additional context

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/a2659fca-48da-411e-9b0f-6b32bafacb24)

**Comment by Ekaterina1994** [comment]
This error happen after migrate data (connected with wrong copy metrics in copied ways). Before migration way was Completed, but after migration metrics was deleted but status wayCompleted didnot changed. 
@tritonJS826  How will be better to correct this? We can add crutch to the front or better to change datas in database?

**Comment by tritonJS826** [comment]
Better to fix it on the database

**Comment by tritonJS826** [comment]
I checked and I see that way is not become completed if all metrics marked as finished. @Ekaterina1994  Why?

**Comment by Ekaterina1994** [comment]
Need to add on backend

**Comment by tritonJS826** [comment]
For now status recalculated after any metric change. Hope it is enoug
