### ISSUE TITLE
day reports: compact view

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#756]
add design for compact view

**Comment by vikpak89** [comment]
work on design of Job done: alignment and spacing between elements

**Comment by tritonJS826** [comment]
* In blocks too much free space on the right side
*  we discussed  a little bit different title as I remember  (date on the first place instead of alias)
* lets use numbers instead of month name (April -> 04), let's save some resources on translation logic
* let's move create new day report button to the left side

**Comment by Ekaterina1994** [comment]
Blocked by #926

**Comment by Ekaterina1994** [comment]
Unblocked
