### ISSUE TITLE
User's ways: 'own', 'favorite', 'mentoring' collection button titles and way header start with a lowercase letter

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#758]
## Steps to reproduce

1. Open any user personal area page, for example: https://mastersway.netlify.app/user/ef04a838-6c71-3e0b-424b-8c590012e4f0
2. Check collection titles and way headers for displayed ways depending on the selected collection:  'own', 'favorite', 'mentoring'.

## Actual result

Way headers and collection button names start with a lowercase letter.

## Expected result

Way headers and collection button names starts with a capital letter.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/78396338-8784-490a-8128-f9d0fbb7b578)

**Comment by Ekaterina1994** [comment]
Need to move logic to converters (with possibility to change laguage of names of default collections)

**Comment by tritonJS826** [comment]
will be fixed after implementing translation for this interface
