### ISSUE TITLE
The element blinks when the response from the backend is confirmed

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#763]

**Comment by n144astya** [comment]
the element needs to be set to wait longer for a response from the backer. 


Environment : Windows 10 Version 22H2 Google Chrome  121.0.6167.161

Preconditions : 1) log in2)go to way https://mastersway.netlify.app/way/e727caee-f2c6-61fe-8c35-1e559287052b
Reproduction steps : 1 ) create a plan2) click to mark plan as completed3) click to buttom "Copy to jobs done" at dialog window
Actual result : The plan copy to jobs done
Expected Result : 1) check is blinks2) The plan copy to jobs done
Severity : Low / Trivial
Priority : Low

https://www.awesomescreenshot.com/video/27108707?key=c0a732ea0295901fb590d3d750765728

**Comment by Ekaterina1994** [comment]
@n144astya Sorry, but video is not working. And I can't reproduce this bug according steps. Please add more details and check)

**Comment by n144astya** [comment]
Yes, I needed space in the free program and I cleaned up old videos. I didn’t think that so old video was still in the works. Having gone through the reproduction steps, I will say that there is no blinking. Apparently the reason was the same with task #958. I think it was fixed.
