### ISSUE TITLE
All users page_Search by email and by name: some displayed user data does not contain the entered characters

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#764]
## Steps to reproduce

**- For Search be email:**
1. Page "All users" is open.
2. Some users exist.
3. Type '_ka_' to the first search field: 'Search by email'.
4. Click 'Load more' button.
5. Compare amounts of filterd users, 'Users' ans 'Total found' titles, user emails.

**- Repeat steps for Search by name, type 'я' into search be name field.**

## Actual result

Not all filtered emails contain the entered characters.
A total of 20 users are displayed; the first 11 correspond to the set filter criteria.
Titles: 'Users' = 20, 'Total found' = 11.

## Expected result

The search filter by email works correctly.

**Search by email:**
![Image](https://github.com/tritonJS826/masters-way/assets/115548501/d4fcbf55-d8f8-48fa-b1f6-38224db06360)

https://github.com/tritonJS826/masters-way/assets/115548501/70b14f05-f5c0-443e-a8de-afd1d1e5d3b8

**Search by name:**

https://github.com/tritonJS826/masters-way/assets/115548501/abb5aa32-51ce-45af-bdd6-40d1dad37df2

**Comment by tritonJS826** [comment]
fixed, the problem was in the filters on the client side

**Comment by EkaterinaSokolova-V** [comment]
fixed
