### ISSUE TITLE
All users (Language interface)

### ISSUE THREAD

**Issue by vdruda** [tritonJS826/masters-way#767]

**Comment by vdruda** [comment]
Steps
1.Click on the burger menu
2.Open "All users" page

Expected result
1.The section interface "All users

Actual result
1.In the card view no have translate 

Comment
If choose table view all interface translated, but in card view interface dose not translated

![Image](https://github.com/tritonJS826/masters-way/assets/141385609/65879138-8669-47c3-a840-cfc9e8ba159b)

**Comment by vdruda** [comment]
The same problems with UK and KA language

**Comment by vdruda** [comment]
The same problems with UA and KA language

![Image](https://github.com/tritonJS826/masters-way/assets/141385609/ead11ff7-7333-48b2-b52c-b24a8f982ed6)

**Comment by vdruda** [comment]
Fixet

**Comment by EkaterinaSokolova-V** [comment]
fixed
