### ISSUE TITLE
User profile (Language interface)

### ISSUE THREAD

**Issue by vdruda** [tritonJS826/masters-way#768]

**Comment by vdruda** [comment]
Steps
1.Click on the burger menu
2.Open "All users" page
3.Open user profile

Expected result
1.The section interface "User profile" translate

Actual result
1.Some of sections not translate


![Image](https://github.com/tritonJS826/masters-way/assets/141385609/f7927b0b-2a20-4723-b553-f47033b97c3d)

**Comment by vdruda** [comment]
The same problems with UA and KA language

![Image](https://github.com/tritonJS826/masters-way/assets/141385609/ee0a8753-bfc2-4a73-8173-5483bf1f93d8)

**Comment by EkaterinaSokolova-V** [comment]
The same for RU language.

**Comment by EkaterinaSokolova-V** [comment]
@Ekaterina1994 , please check "Status" filter and "New collection"-collection created by default for RU, UA:

https://github.com/tritonJS826/masters-way/assets/115548501/0d793376-7dce-4e37-81fe-cd53e6c25c7c

**Comment by Ekaterina1994** [comment]
@EkaterinaSokolova-V Переводятся только дефолтные коллекции.  Коллекция New collection - это кастомная коллекция, мы не можем переводить кастомные коллекции. 
По поводу select - если про то, что обрезается буква, то лучше завести отдельный баг, так как не связано с переводом

**Comment by EkaterinaSokolova-V** [comment]
@Ekaterina1994 , а можно при создании такой кастомной коллекции с названием по умолчанию учитывать выбранный язык?
По Status select завела баг [#885](https://github.com/tritonJS826/masters-way/issues/885)

**Comment by tritonJS826** [comment]
Одобрено, сделаем!)

**Comment by EkaterinaSokolova-V** [comment]
> Одобрено, сделаем!)
Баг репот уже есть:
[#802](https://github.com/tritonJS826/masters-way/issues/802)

Этот тикет Done

**Comment by Ekaterina1994** [comment]
Done
