### ISSUE TITLE
Settings (Language interface)

### ISSUE THREAD

**Issue by vdruda** [tritonJS826/masters-way#769]

**Comment by vdruda** [comment]
Steps
1.Click on the burger menu
2.Open "Settings" page
3.Hover over "Test notification"

Expected result
1.The section interface "Settings" translated

Actual result
1.Some of sections not translate

![Image](https://github.com/tritonJS826/masters-way/assets/141385609/6c164a12-6251-49cc-ada5-2c9abe598eab)

**Comment by vdruda** [comment]
The same problems when u choose UA and KA language

![Image](https://github.com/tritonJS826/masters-way/assets/141385609/1180fe30-804e-4793-8218-de9730f15349)

**Comment by vdruda** [comment]
Language translate fixed. Need to move tooltip in right up conner from button "Test notification"

**Comment by tritonJS826** [comment]
I changed styles a little, but this page is just stub

**Comment by EkaterinaSokolova-V** [comment]
done
