### ISSUE TITLE
Tooltip's text "Click to mark plan as completed" has unnecessary period at the end of a sentence

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#774]

**Comment by evgenia7p** [comment]
Preconditions
User has a way with planned job 

Steps
Hover over the check box in Plans block in Reports section

Expected result
Text "Click to mark plan as completed" is displayed as a tooltip

Actual result
Text "Click to mark plan as completed." is displayed as a tooltip (unnecessary period at the end of a sentence )


![Image](https://github.com/tritonJS826/masters-way/assets/163824877/e04f5a7a-a292-4abb-98a5-24f46ee0a82d)

**Comment by Ekaterina1994** [comment]
Was done? Can't find the mistake in the demo

**Comment by evgenia7p** [comment]
> Was done? Can't find the mistake in the demo

Yes, it was done

**Comment by evgenia7p** [comment]
Done
