### ISSUE TITLE
Metrics: Date refered to the completed metric is not correctly used

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#776]
Date refered to the completed metric is not correctly used in metrics created before 2024-04-06

**Comment by evgenia7p** [comment]
Steps:
1.	Open any way created before 2024-04-06 with a completed goal
2.	Hover over completed goal

Expected results:
Text "Done date yyyy-mm-dd" is displayed as a tooltip, the date corresponds to the date when the goal was ticked



![Image](https://github.com/tritonJS826/masters-way/assets/163824877/24620b4c-cb49-418f-bb5b-be1848a5312c)

Actual results:
Tooltips display unrealistic dates, the format yyyy-mm-dd is not used

**Comment by tritonJS826** [comment]
looks like migration related issue

**Comment by tritonJS826** [comment]
replaced automatically on 2024-04-30 19:30:20.748 (134 metrics affected), looks like it is migration-related issue, so, there is no make sense for now handle each metric manually, I hope. Anyway the job finished.
