### ISSUE TITLE
UX/UI_Statistics: Check-boxes in the All statistics section aren't clickable on all area because of element overlapping

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#778]

**Comment by evgenia7p** [comment]
Preconditions
User is authorized. User's way is created and opened. Some day reports with using tags exist

Steps
1. Open All statistics section
2. Click on the bottom area of any check-boxes in the Labels statistic blocks

Expected result
All check-boxes in the all statistics section are clickable on all area

Actual result
Check-boxes in the Labels statistic blocks of the all statistics section aren't clickable on all area because of element overlapping


![Image](https://github.com/tritonJS826/masters-way/assets/163824877/88732f4d-5d0c-4e6b-8421-f2941de4820e)

**Comment by Ekaterina1994** [comment]
Need to analize libraries for charts

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
