### ISSUE TITLE
Separate custom and default vollections

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#782]

**Comment by MarieKulik** [comment]
I separated custom and default collection @tritonJS826 
Link: https://www.figma.com/file/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?type=design&node-id=1489%3A36308&mode=design&t=r9WanMBrabf0lBrO-1

**Comment by Ekaterina1994** [comment]
Done

**Comment by EkaterinaSokolova-V** [comment]
done
