### ISSUE TITLE
add flag-marks on user card if it is a mentor

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#785]
- [ ] Add flag
- [ ] Align design for user card

**Comment by Ekaterina1994** [comment]
Not clear. Please add links on figma or add comment what should to do developers)

**Comment by tritonJS826** [comment]
mentor flag - green

**Comment by tritonJS826** [comment]
Need token for green color

**Comment by vikpak89** [comment]
creating token for bookmarks 

https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=2596-38020&t=9n8J9WzzyiowONLs-1

**Comment by Ekaterina1994** [comment]
Blocked by #926

**Comment by tritonJS826** [comment]
just isMentor green flag will be enough for now

**Comment by Ekaterina1994** [comment]
UNBLOCKED

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
