### ISSUE TITLE
align "проектирование" folders, just recheck make clear classification of pages, components etc.

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#787]
for example I don't see users page for now

**Comment by tritonJS826** [comment]
it looks good enough

**Comment by Ekaterina1994** [comment]
Написала комментарии в файлах Components и Pages с предожениямим по улучшению структуры данных в фигме)

**Comment by vikpak89** [comment]
![Image](https://github.com/tritonJS826/masters-way/assets/167992048/f191cd7a-df13-43be-acb2-42129dc7c91a)
