### ISSUE TITLE
Add Pricing plans page

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#789]
- [ ] Add page to routing
- [ ] Add basic structure (title and subtitle with translating on laguages) 
- [ ] Add pricing
https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=4177-6379&t=Yk6NdFgH5xYbZ8LP-4

**Comment by vikpak89** [comment]
@tritonJS826 I need details on the content on this page: how many pricing programs will there be, what information besides prices will be on the page

**Comment by tritonJS826** [comment]
we need something simple like here https://github.com/pricing. 
Points: 
https://docs.google.com/spreadsheets/d/1rtwQJgdxyqh2uDWpNzCrxiUORe49oxISsd2shuq0UMU/edit#gid=0

**Comment by vikpak89** [comment]
https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=4177-6379&t=tERfHRrHWvCrb68p-1

**Comment by Ekaterina1994** [comment]
@vikpak89 Пожалуйста, напиши, в группе в телеграме, как будет готов план, чтобы разработчики понимали, что можно его делать)

**Comment by vikpak89** [comment]
@Ekaterina1994 https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=4650-8752&t=Upmq1yMh4wdPQVbG-1

**Comment by Ekaterina1994** [comment]
Done
