### ISSUE TITLE
RU language (interface)_user way page: some buttons, text are not translated or need to be corrected

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#793]
## Preconditions
1. Log in.
2. Open user way page.
3. Russian language chosen.

## Steps to reproduce

1. Select Delete way from actions menu -  the text of pop-up window is not translated.
2. Click Add tag for any job -  the text of Cancel/Save buttons is not translated.
3. Hover over Jobs done - "способ" replaced by "путь".
4. Hover over Plans - "способ" replaced by "путь". 

## Actual result

Some buttons, text are not translated or need to be corrected ("Jobs done" and "Plans" tooltips).

## Expected result

The "User way" interface is translated into Russian.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/047926ff-79cd-410f-9fd3-3767ce7ddf7d)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/4c0b47fc-7ada-44e7-88c9-8cd23fbfbe50)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/e6d23d5c-a27f-47ca-982c-83679a0a81f3)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/372dafa6-285d-4d96-8014-7d56eaf7268e)

**Comment by vdruda** [comment]
Same problems with UA language

![Image](https://github.com/tritonJS826/masters-way/assets/141385609/a873876e-14f7-4ac9-b222-25282da44155)

**Comment by EkaterinaSokolova-V** [comment]
Fixed
