### ISSUE TITLE
RU Language (interface)_All Users page: spelling in translation needs to be corrected

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#794]
## Steps to reproduce

1. Open All Users page.
2. Select RU language.
3. Click Card view mode button.

## Actual result

spelling in translation needs to be corrected: "1 собственных путей", "2 собственных путей" etc.

https://github.com/tritonJS826/masters-way/assets/115548501/8e74bfeb-f0b8-4633-9fcf-70f90b61793e

**Comment by Ekaterina1994** [comment]
Done

**Comment by EkaterinaSokolova-V** [comment]
fixed
