### ISSUE TITLE
Statistics: the chart does not show tasks completed on the first day

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#795]

**Comment by n144astya** [comment]
![Image](https://github.com/tritonJS826/masters-way/assets/142949669/ac46a874-3a91-49fc-b99c-3756b6ec1ff4)



![Image](https://github.com/tritonJS826/masters-way/assets/142949669/ea33511e-c026-4632-af8b-ec906b8c0b83)

**Comment by Ekaterina1994** [comment]
Done

**Comment by vdruda** [comment]
Done
