### ISSUE TITLE
LinkedIn page not opens in a new tab on "About project" page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#796]
## Description
LinkedIn page not opens in a new tab on about project page in "How can you cooperate with us?" block.

## Steps to reproduce

1. Open [about project](https://mastersway.netlify.app/aboutProject) page
2. Expand "How can you cooperate with us?" block
3. Click on LinkedIn link

![Image](https://github.com/tritonJS826/masters-way/assets/4976837/df82cf18-228d-4e0c-8a4f-f9a63373829b)

## Actual result

LinkedIn page opens in same tab

## Expected result

LinkedIn page opens in a new tab

**Comment by tritonJS826** [comment]
+ All md formatted anchors should lead to the new tab.

**Comment by Ekaterina1994** [comment]
Done

**Comment by EkaterinaSokolova-V** [comment]
fixed
