### ISSUE TITLE
YouTube page not opens in a new tab on "About project" page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#797]
## Description
YouTube page not opens in a new tab on "About project" page in "How to fill the way correctly?" block.

## Steps to reproduce

1. Open [about project](https://mastersway.netlify.app/aboutProject) page
2. Expand "How to fill the way correctly?" block
3. Click on the hyperlink "Here"

![Image](https://github.com/tritonJS826/masters-way/assets/4976837/7305f334-af26-4f63-b151-2fe021e4f81c)

## Actual result
YouTube page opens in same tab

## Expected result
YouTube page opens in a new tab

**Comment by tritonJS826** [comment]
Lets discuss it with the team

**Comment by tritonJS826** [comment]
duplicate of #796

**Comment by EkaterinaSokolova-V** [comment]
closed as duplicate, will be fixed in https://github.com/tritonJS826/masters-way/issues/796
