### ISSUE TITLE
Tooltip "Time spent on job (minutes)" in the lowest row of Reports table isn't fully visible and provokes the appearance of unnecessary vertically scrolling

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#800]

**Comment by evgenia7p** [comment]
Preconditions
User is authorized. User's way is created and opened. Some day reports exist

Steps

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/1a5cadce-9764-46d4-81d1-0cf84f710609)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/47288bd7-e594-4512-b47c-bbe21fd4efb4)



https://github.com/tritonJS826/masters-way/assets/163824877/fa2a8c35-fbe5-4ae7-aed8-e6c4115cdb87


Hover over "Time spent on job (minutes)" in the lowest row of Reports table

Expected result
Tooltip "Time spent on job (minutes)" is displayed correctly

Actual result
Tooltip "Time spent on job (minutes)" isn't fully visible and provokes the appearance of unnecessary vertically scrolling

**Comment by Ekaterina1994** [comment]
@evgenia7p  Can't to reproduce. Need more details

https://github.com/tritonJS826/masters-way/assets/57002521/1719540c-9858-4c0a-a90e-811857394218

**Comment by pp2amd6** [comment]
Can't reproduce
