### ISSUE TITLE
User skill tags: incorrect display of skill tags

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#801]
## Steps to reproduce

1. Log in.
2. Create skill tag.
3. Open personal area of any other user.

## Actual result
The newly created tag is displayed on any personal area user's page.

4. Open this user personal area page.
5. Log out.

## Actual result
This tag is not displayed on the user page.

## Expected result

Skill tags are displayed regardless of user authentication and only for the user who created them.

https://github.com/tritonJS826/masters-way/assets/115548501/1796e90a-63cf-4b60-acc3-c83df08dfe40

**Skill tags are displayed on way cards, but not on user personal area:**

![Captura de pantalla 2024-05-01 182739](https://github.com/tritonJS826/masters-way/assets/115548501/8540f9a1-be0e-4710-aead-f0fd03acfc8a)
![Captura de pantalla 2024-05-01 182815](https://github.com/tritonJS826/masters-way/assets/115548501/cfb030a0-76c5-4fe7-aa78-d2651d65b4cc)

**Comment by tritonJS826** [comment]
fixed
