### ISSUE TITLE
Statistics: floating bug with an extra date appearing on the report

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#811]
The bug was discovered around 01:00 (gmt+3). At 16:22 the chart remains the same. 

![Image](https://github.com/tritonJS826/masters-way/assets/142949669/983f9102-daf9-4cfc-84d3-780fede9b305)

![Image](https://github.com/tritonJS826/masters-way/assets/142949669/6f4e0faf-bc97-4eb4-b29d-ce7308f76df2)

**Comment by AKiroi** [comment]
fixed #795

**Comment by vdruda** [comment]
Done
