### ISSUE TITLE
About our project_Our team section: depending on the screen resolution, all team members are not displayed

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#814]
## Steps to reproduce

1. Open About our project page: https://mastersway.netlify.app/aboutProject
2. Change (reduce) screen resolution.
3. Check that all team members are visible.

## Actual result

1. All team members are visible at any screen resolution (using horizontal scrolling).
2. Display of team members are not horizontally aligned.

## Expected result

As soon as horizontal scrolling appears, the display of team members is cut off on the left and all team members are not displayed.

https://github.com/tritonJS826/masters-way/assets/115548501/3b018767-970c-4750-9ba4-a989455714f9

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/a899d592-aa71-4d74-8e22-aa0e15941cd0)

**Comment by tritonJS826** [comment]
ашчув
