### ISSUE TITLE
Statistic/Labels statistic: Interest on Jobs amount is entered from the Time (minutes) column

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#815]
The second column shows the number of completed task with the label from the first column according to the report and the percentage in relation to "Total finished jobs"

**Comment by n144astya** [comment]
![Image](https://github.com/tritonJS826/masters-way/assets/142949669/12dcc67b-8198-4c78-b24b-243d8f17f34c)

**Comment by tritonJS826** [comment]
not clear what the what the issue
