### ISSUE TITLE
Add mobX to the project

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#816]
- [x] Change Theme by using mobX as a global store
- [x] Change Language by using mobX as a global store

**Comment by pp2amd6** [comment]
@tritonJS826 @Ekaterina1994 how QA Team should / can test that? :)

**Comment by Ekaterina1994** [comment]
Need to check updating theme, language and user logic

**Comment by EkaterinaSokolova-V** [comment]
`done
