### ISSUE TITLE
No uniformity in the text of tooltips in Russian language

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#817]

**Comment by evgenia7p** [comment]
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/299fbd77-3699-4357-945c-bff171d00c65)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/32995551-eb31-4397-825e-cd7567c5d15d)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/d43716e6-bd31-4717-aa18-6e963f20ac82)

**Comment by Ekaterina1994** [comment]
Not clear bug. Please be more informative

**Comment by evgenia7p** [comment]
> Not clear bug. Please be more informative

Sorry, I added steps for reproduce

**Comment by evgenia7p** [comment]
Done
