### ISSUE TITLE
API: creating new user route not found

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#828]
## Description

When calling the method for creating a new user, we receive an error stating that the route was not found

## Steps to reproduce

1. Fill data for request fields
2. Send request

Example:
![Image](https://github.com/tritonJS826/masters-way/assets/4976837/06b27852-31f6-46dd-9584-0602f2b1b6ab)

## Actual result
Error "The specified route /api/users not found" received

![Image](https://github.com/tritonJS826/masters-way/assets/4976837/e215e0ef-52fc-49c1-8111-a089c8ee9ec0)

## Expected result

The request is running, there are no errors associated with the route

**Comment by tritonJS826** [comment]
This route blocked bc for now we are creating user through firebase services, so it is ok for now. In future we will implement authorisation on the back, I hope after implementing all MVP features
