### ISSUE TITLE
API: it is possible to delete any user

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#830]
## Description

It is possible to delete any user using API method

## Preconditions

1. Create user (log in via Google or use API)

## Steps to reproduce

1. Prepare DELETE http method for /users route
2. Send request

Example:
`DELETE /api/users/7da03585-1846-4e87-8d40-2388f44a451a`

## Actual result
The specified user has been deleted

## Expected result
User can`t be deleted without authorization.
You can only delete users you created.

**Comment by tritonJS826** [comment]
Endpoint removed
