### ISSUE TITLE
User way: Error on renaming goal metric in new created way

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#831]
## Description
We get an error when renaming a goal in a new way

## Preconditions

1. Go to own user profile page

## Steps to reproduce

1. Click on "Create new way" button
2. On new created way page click "Add new goal metric" button
3. Double click on new goal record and enter goal name

## Actual result
Getting HTTP 500 Error on PATCH /metrics method call
But after page reload entered goal name presented correctly

![image](https://github.com/tritonJS826/masters-way/assets/4976837/2402f399-aa36-4b98-bc06-b3e9ab66d67c)
![image](https://github.com/tritonJS826/masters-way/assets/4976837/28637d64-7f6c-46a0-b38e-6fb02df56f3e)

Request payload:
```
{
    description: "1",
    doneDate: null
}
```

Response body:
```json
{
    "error": "parsing time \"\" as \"2006-01-02T15:04:05.999Z\": cannot parse \"\" as \"2006\""
}{
    "uuid": "43b27b6b-8d94-4c30-8696-44090bed0bb8",
    "createdAt": "2024-05-10 14:50:28.387407 +0000 +0000",
    "updatedAt": "2024-05-10 14:50:30.731926 +0000 +0000",
    "description": "1",
    "isDone": false,
    "doneDate": null,
    "estimationTime": 0
}
```

## Expected result

Goal renamed without error

**Comment by tritonJS826** [comment]
fixed
