### ISSUE TITLE
Login: FirebaseError appears when user close Google auth window

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#832]
## Description
FirebaseError appears when user close Google auth window

## Preconditions
1. Create Google account if needed
2. User should be logged out

## Steps to reproduce
1. Open application site
2. Press "Login" button (or "Start for free!" button or "Try now!" button if user on home page)
3. Close Google auth window

## Actual result
FirebaseError appeared after user close Google auth window
![image](https://github.com/tritonJS826/masters-way/assets/4976837/ca2232e1-c8da-4d88-a0ff-895425c4f959)

![image](https://github.com/tritonJS826/masters-way/assets/4976837/9f11df56-fc5c-4982-aa76-a184b0a688db)

## Expected result
Closing the window does not cause an error

**Comment by Ekaterina1994** [comment]
Connected with issues #435 and #710

**Comment by tritonJS826** [comment]
duplicate of 435

**Comment by pp2amd6** [comment]
Closed because #435 moved to backlog
