### ISSUE TITLE
Job tags: a tag with a long name overlaps the adjacent element

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#833]
## Description

A tag with a long name overlaps the adjacent element on way page.

## Preconditions

1. User logged already
2. At least one way created
3. At least two job tags created
4. At least one day report created

## Steps to reproduce

1. Create new job
2. Click on "Add tag label"
3. Modal window with tags list presented

## Actual result
A tag with a long name overlaps the adjacent element

![image](https://github.com/tritonJS826/masters-way/assets/4976837/7536024a-359a-4226-9778-2e60a8fb1e4f)

## Expected result

Tags are displayed without overlapping each other

**Comment by Ekaterina1994** [comment]
Done

**Comment by EkaterinaSokolova-V** [comment]
Fixed
