### ISSUE TITLE
Way collection: collection name not fit in button on user page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#850]
## Description

If collection name is too long, for example have max length accordingly [restrictions](https://docs.google.com/spreadsheets/d/1rtwQJgdxyqh2uDWpNzCrxiUORe49oxISsd2shuq0UMU/edit#gid=0), name goes beyond the boundaries of the button

## Preconditions

1. Log in into application
2. Go to user page

## Steps to reproduce

1. Create custom collection
2. Select4ed created collection
3. Press " Rename collection" button and enter long name, e.g. "Minus alias veniam tempore. Odio maiores quaerat s"
4. Press "OK" button

## Actual result

Name goes beyond the boundaries of the button

![Image](https://github.com/tritonJS826/masters-way/assets/4976837/e7ac3442-0918-4306-adc5-6b88ba77a455)

## Expected result

Name fit in button

![Image](https://github.com/tritonJS826/masters-way/assets/4976837/f5a8c4bb-c05a-4ae5-85ae-8f7d7a7e6e50)

**Comment by tritonJS826** [comment]
Should be fixed in #597  (after redisign)
