### ISSUE TITLE
Placeholder "Empty markdown! Double click on me!" in Reports section is not translated into Russian, Ukrainian and Georgian languages

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#877]
Preconditions
User is authorized. User's way is created and opened. 

Steps
1. Click on “Create new day report” button
2. Click on “Add job done”
3. Click on “Add plan”
4. Click on “Add problem”
5. Click on “Add comment”
6. Switch Russian language
7. Switch Ukrainian language
8. Switch Georgian language

Expected result
The placeholder"Empty markdown! Double click on me" of Jobs done, Plans, Problems and Comments sections is translated into Russian, Ukrainian and Georgian languages

Actual result
The placeholder"Empty markdown! Double click on me" is displayed in English for all language versions

**Comment by evgenia7p** [comment]
Preconditions
User is authorized. User's way is created and opened. 

Steps
1. Click on “Create new day report” button
2. Click on “Add job done”
3. Click on “Add plan”
4. Click on “Add problem”
5. Click on “Add comment”
6. Switch Russian language
7. Switch Ukrainian language
8. Switch Georgian language

Expected result
The placeholder"Empty markdown! Double click on me" of Jobs done, Plans, Problems and Comments sections is translated into Russian, Ukrainian and Georgian languages
Actual result
The placeholder"Empty markdown! Double click on me" is displayed in English for all language versions



![Image](https://github.com/tritonJS826/masters-way/assets/163824877/b56024a5-2e3f-4724-bc3f-2b8dc693dc4a)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/2c3d3132-81d1-4d6f-a5d5-884329f0a2d7)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/0107aea4-9f41-46e1-b8ae-ac1bff3e8592)

**Comment by tritonJS826** [comment]
wlll be fixed in #876

**Comment by evgenia7p** [comment]
> wlll be fixed in [#876](https://github.com/tritonJS826/masters-way/issues/876)

Ok
