### ISSUE TITLE
Statistics: Titles in Statistics section extend beyond their fields in Russian and Georgian language versions

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#878]
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/0437a533-fd8e-4051-a990-f23702206e2a)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/b704521e-4be7-43af-961a-54b6ce91653b)

**Comment by Ekaterina1994** [comment]
На данный момент в Статистике  уменьшены паддинги по сравнению с дизайном (так как не готовы на них токены и используются старые значения). Просто изменить слова не решит проблему, так как при увеличении паддингов (в соответствии с дизайном в фигме), тексту опять не будет хватать места (особенно на восточных языках (грузинкий, в дальнейшем китайский и тд (там буквы шире, чем русские и английские).  Также нужно продумать как будет выглядеть статистика если значения будут не 33, а например 1000h в каждой из ячеек))

**Comment by vikpak89** [comment]
I changed the layouts with numbers and signatures, now the numbers should fit more and the translation should not go beyond the scope, but you need to check

https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=1490-37525&t=kgZlUjAuaCIvLDA9-1

**Comment by Ekaterina1994** [comment]
Done

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
