### ISSUE TITLE
Language: "Add tag" of Jobs done block in Reports section is not translated into Russian, Ukrainian and Georgian languages

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#879]
Preconditions
User is authorized. User's way is created and opened. 

Steps
1. Click on “Create new day report” button
2. Click on “Add job done”
3. Switch Russian language
4. Switch Ukrainian language
5. Switch Georgian language

Expected result
"Add tag" is translated into Russian, Ukrainian and Georgian languages

Actual result
"Add tag" is displayed in English for all language versions

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/93a04117-f6ab-4df8-9007-a1b7689e57e3)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/5b58e6fb-57fd-49bb-a644-4ea4381de876)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/07edb40f-06c5-41fd-9b97-e4f9f938c8fe)

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
