### ISSUE TITLE
"Participants" and “Participants ways” are not translated into Russian, Ukrainian and Georgian languages

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#880]
Preconditions
User is authorized. User's way is created and opened. 

Steps
1. Switch Russian language
2. Switch Ukrainian language
3. Switch Georgian language

Expected result
"Participants" and “Participants ways” are translated into Russian, Ukrainian and Georgian languages

Actual result
"Participants" and “Participants ways” are displayed in English for all language versions

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/7eaf219b-4072-4d3c-8998-3e3f7548169f)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/fcfbbcc5-2fa4-4648-a1f4-4cca434438f8)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/7473fa19-ebfb-45bd-b4ee-973eca31d832)

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
