### ISSUE TITLE
Language: "Time spent by day (minures/date)" in Statistics section is not translated into Russian, Ukrainian and Georgian languages

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#881]
Preconditions
User is authorized. User's way is created and opened. Some day reports exist

Steps
1. Switch Russian language
2. Switch Ukrainian language
3. Switch Georgian language

Expected result
"Time spent by day (minures/date)" in Statistics section is translated into Russian, Ukrainian and Georgian languages

Actual result
"Time spent by day (minures/date)" in Statistics section is displayed in English for all language versions

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/ed4002a0-870b-41d5-9ede-81305cd18d9e)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/4c6b6fda-d0dc-4ed3-95bd-2b5c04e985c7)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/a4f56b1c-93ad-47e4-8d7c-b415d44b1286)

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
