### ISSUE TITLE
Statistics: It is impossible to read the full text of some titles in Statistics section

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#884]
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/b564e57d-5181-4f67-a86d-1a4f292a1c47)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/3a336662-6fe9-455a-b025-9ef11e22f474)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/b22387d0-d02a-4bc1-b832-088b02329690)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/30746f86-fc3d-4326-8dc6-eb158b887a0e)

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
