### ISSUE TITLE
User personal area / All ways page: the title of the last Status menu item is not fully displayed for RU and UA.

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#885]
## Preconditions

Select RU language.
**Than repeate for UA.**

## Steps to reproduce

1. Open User personal area / **Repeate for All ways page**
2. Open Status select.

## Actual result

The title of the last menu item is not fully displayed.

## Expected result

All displayed items of the menu are readable.

## Additional context

In UA the last menu item is translated differently on the All ways and User profile pages.

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/00500716-a53b-463d-ae54-3b70be5b173e)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/a63a6693-6259-497d-9f8c-096945fde2e0)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/ebaa2f48-5b57-457d-8c9a-07e6a73a2841)

![Image](https://github.com/tritonJS826/masters-way/assets/115548501/55e80ed4-2901-441c-b2d6-53eca42f6edf)

https://github.com/tritonJS826/masters-way/assets/115548501/f75ffc32-15cf-47ba-bc66-6b4141593404

**Comment by Ekaterina1994** [comment]
Done
