### ISSUE TITLE
DayReports: sort jobs, plans, problems, comments by created date on the front when creating composite way

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#897]
After reloading page, order of jobs, plans, problems, comments could be changed. We shoul dhave only one flow for both of them for now

**Comment by n144astya** [comment]
Environment: firefox Версия 125.0.1 (64-битная), Windows 10 Version 22H2

Actual result;
Home page: background image is not displayed


![Image](https://github.com/tritonJS826/masters-way/assets/142949669/96535519-fd5f-494a-b4c3-970242a97e8c)

Home page doesn't match the layout

![Image](https://github.com/tritonJS826/masters-way/assets/142949669/3c3f3e81-29ad-4165-8c18-9f94ac20485a)

**Comment by pp2amd6** [comment]
@n144astya 

> Home page doesn't match the layout

#954

**Comment by vdruda** [comment]
Done

**Comment by vdruda** [comment]
Done. Migrationis done, works correctly local branch and main branch
