### ISSUE TITLE
The app should work in popular browsers (safari, firefox, edge, chrome)

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#898]

**Comment by Ekaterina1994** [comment]
Method DateUtils.getShortISODateValue return an error "Invalid date" in Firefox. It because of format of date. Need to find a method to convert date into valid format.

**Comment by algrinkevich** [comment]
The backend sends response with malformed dates (timezone offset is repeated 2 times). There are 2 ways to solve this issue:
1. Fix on the backend side;
2. Make workaround on the frontend side.

@Ekaterina1994 What is preferred way?

![Image](https://github.com/tritonJS826/masters-way/assets/8752900/a1d9cc7c-e89e-4399-8872-ef2423529ee0)

**Comment by Ekaterina1994** [comment]
As I know on backend date written in format 2024-04-06 19:39:29.079

@tritonJS826  Am I wrong?

**Comment by tritonJS826** [comment]
fixed, will be delivered today (2024-05-27) evening

**Comment by tritonJS826** [comment]
Should work in firefox, please check in safary and edge

**Comment by n144astya** [comment]
![image](https://github.com/tritonJS826/masters-way/assets/142949669/5b70ee23-278d-4d39-9df0-521103c0dea0)

Actual result;
Home page: firefox all errors are repeated

AND ### ASAP
All users and All way pages do not open
![image](https://github.com/tritonJS826/masters-way/assets/142949669/2d413087-425a-4d8f-88e1-98ce073dde47)

**Comment by algrinkevich** [comment]
1. First issue: pictures.
> Home page: background image is not displayed

This is another issue (not related to this task). If you try to open the app in Incognito mode in Chrome, the pictures are not displayed here as well. The pictures stored on Google are not loaded if a user is not logged in. @n144astya probably it's needed a new issue if it doesn't exist.
<img src="https://github.com/tritonJS826/masters-way/assets/8752900/7af7c1b8-0240-41b8-9817-68cd6e54a738" width="500" />

2. Second issue: "Invalide Date" in Safari
@tritonJS826 According to the [ISO 8601 standard](https://www.w3.org/TR/NOTE-datetime-970915), there is no space between time and timezone offset. Our dates have spaces and webkit fails to parse the string. 
<img src="https://github.com/tritonJS826/masters-way/assets/8752900/38802ecd-925d-4bc1-b24f-ce552176a0d1" width="500" />

**Comment by pp2amd6** [comment]
> This is another issue (not related to this task). If you try to open the app in Incognito mode in Chrome, the pictures are not displayed here as well. The pictures stored on Google are not loaded if a user is not logged in. @n144astya probably it's needed a new issue if it doesn't exist.

#954

**Comment by tritonJS826** [comment]
@Ekaterina1994 probably this should help
