### ISSUE TITLE
Add "privacy policy" link to the footer

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#901]

**Comment by vikpak89** [comment]
@tritonJS826 где именно добавить? ссылкой или просто написать в футере словами?

**Comment by vikpak89** [comment]
adding an information about Privacy policy and terms and conditions 

https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=2802-11117&t=9n8J9WzzyiowONLs-1

**Comment by Ekaterina1994** [comment]
Done
