### ISSUE TITLE
Youtube button in the footer of the site doesn't lead to the application video channel

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#905]
Steps
Click on the Youtube button in the footer of the site 

Expected result
Youtube button leads to  the page https://www.youtube.com/channel/UCIC15w0_bFavQKtQZhRKTUw 

Actual result
Youtube button leads to the page https://www.youtube.com/watch?v=DiNNQol15ds&list=PL7eqEW04iXMV2tu_JYAIwerepUTZJjciM&index=3

**Comment by tritonJS826** [comment]
fixed

**Comment by evgenia7p** [comment]
Checked
