### ISSUE TITLE
Fix Select according design(check tokens)

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#921]

**Comment by vikpak89** [comment]
@Ekaterina1994 в чем сейчас проблема? можно приложить скрины?

**Comment by Ekaterina1994** [comment]
@vikpak89 Раньше  у селекта не было обводки и цвет фона secondaryBg сливался в тех случаях, когда, селект использовался на плашках (например, в области фильтров). Сейчас есть границы, поэтому можно переводить карточку в Design Review 
deprecated

**Comment by pp2amd6** [comment]
> Раньше у селекта не было обводки и цвет фона secondaryBg сливался в тех случаях, когда, селект использовался на плашках

![image](https://github.com/tritonJS826/masters-way/assets/4976837/d35e89a1-da24-4e5f-985f-416a0283ebd1)
![image](https://github.com/tritonJS826/masters-way/assets/4976837/a0eaa73f-1c4d-4fa2-82be-4687094545da)

**Comment by Ekaterina1994** [comment]
Need to update styles for select bacground according figma components

**Comment by Ekaterina1994** [comment]
Duplicated in #1057

**Comment by vdruda** [comment]
Done
