### ISSUE TITLE
Deleting and editing collections

### ISSUE THREAD

**Issue by Ekaterina1994** [tritonJS826/masters-way#923]

**Comment by vikpak89** [comment]
Adding kebab-menu for editing of collection cards
https://www.figma.com/design/ukyPUFcecdKzeBcdTHChYk/%D0%9F%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5?node-id=1489-36308&t=64AKPg4OKsiHBuiL-1

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
