### ISSUE TITLE
All users: Search by email and by name don't work correctly

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#925]
## Steps to reproduce

**- For Search be email:**

1. Page "All users" is open.
2. Some users exist.
3. Type 'so' to the first search field: 'Search by email'.
4. Click 'Load more' button.
5. Compare amounts of filterd users, 'Users' ans 'Total found' titles, user emails.

**- Repeat steps for Search by name, type 'нас' into search be name field.**

https://github.com/tritonJS826/masters-way/assets/115548501/0e519468-b87c-48eb-a8fc-81fe899a96af

**Comment by EkaterinaSokolova-V** [comment]
related with [https://github.com/tritonJS826/masters-way/issues/476](url)

**Comment by Ekaterina1994** [comment]
@EkaterinaSokolova-V Can't reproduce, maybe was fixed with other issue

https://github.com/tritonJS826/masters-way/assets/57002521/bbf9374b-5330-4db8-b28c-839c38a44f35

**Comment by EkaterinaSokolova-V** [comment]
Closed
