### ISSUE TITLE
Way description: it should not be possible to create a way tag without a name

### ISSUE THREAD

**Issue by EkaterinaSokolova-V** [tritonJS826/masters-way#930]
## Steps to reproduce

1. log in.
2. Open any way.
3. Click "Add new way tag".
4. In pop-up window click "Ok" without typing the name.

## Actual result

A tag without a name is created.

## Expected result

It is impossible to create a tag without.

https://github.com/tritonJS826/masters-way/assets/115548501/4a13d0ce-561a-4232-a8e0-3639b36081f6

**Comment by Ekaterina1994** [comment]
Need check value, show notification that tag's name is empty  and don't create tag

**Comment by algrinkevich** [comment]
@Ekaterina1994 What do you think about disabling "Ok" button if the input field is empty?

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
