### ISSUE TITLE
User's ways: job breaks down when string contains link markdown used as job name

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#935]
Maybe similar to [729](https://github.com/tritonJS826/masters-way/issues/729)

## Description

Job breaks down when string contains link markdown with empty name part used as job name

## Preconditions

1. Created at least one Way
2. Created at least one Day report in Way

## Steps to reproduce

1. Create new job
2. Enter link markdown with empty name part, e.g. `[](https://google.com)`
3. Click on any part of page for save entered data

## Actual result

The line collapses. You cannot enter a job name.
![](https://private-user-images.githubusercontent.com/4976837/324267911-db954e1a-0eac-4c5c-835d-f17f4587f6fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTM1MjksIm5iZiI6MTcxNjU5MzIyOSwicGF0aCI6Ii80OTc2ODM3LzMyNDI2NzkxMS1kYjk1NGUxYS0wZWFjLTRjNWMtODM1ZC1mMTdmNDU4N2Y2ZmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjRUMjMyNzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2MxYTUwNWU2MmQ3ZmQ5MjViMGUyN2RlMTUxMzUzZmQ2YTQyNWU2NzBiNDQyNjAyYjJkZTdlNTg1OTFiYjUxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CpmIEr01IbPjmFfZNWas3VemULh0F3ssUmNHJwskGx8)

## <a id="expected-result">Expected result</a>

Spaces are trimmed and a placeholder is displayed 
![image](https://github.com/tritonJS826/masters-way/assets/4976837/a6b68e31-237d-4a89-8b96-ed6bfbfdcc9d)

**or** a visually empty line is shown
![](https://private-user-images.githubusercontent.com/4976837/324268281-dba83750-cd60-46d7-a68b-5b9655a0517e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTM1MjksIm5iZiI6MTcxNjU5MzIyOSwicGF0aCI6Ii80OTc2ODM3LzMyNDI2ODI4MS1kYmE4Mzc1MC1jZDYwLTQ2ZDctYTY4Yi01Yjk2NTVhMDUxN2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjRUMjMyNzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDU1MDRkYmE5MGFiNzNmYWFlMjQ0YzBmNzU0OWJlZmRjN2QwOWExYTk2MTE4NTkyMzNlNGNiYjM1MDU0ODRhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8wlgDrJQnZq2tUTlWaZAhiS8L8eKtFBWyCRz0waH5uo)

**or** automatically converted to custom placeholder
![image](https://github.com/tritonJS826/masters-way/assets/4976837/afc4db00-3af3-471d-9b62-2de3025a4794)

**Comment by pp2amd6** [comment]
@tritonJS826 your help needed. Please look at _Expected result_ section

**Comment by Ekaterina1994** [comment]
It's standard behavior of markdown format. Checked it in the previous comment. ))) Let's skip it for now

**Comment by tritonJS826** [comment]
automatically converted to custom placeholder is good enough

**Comment by Ekaterina1994** [comment]
Done
