### ISSUE TITLE
way metrics: Goal breaks down when string contains link markdown

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#936]
## Description

Goal breaks down when string contains link markdown with empty string as name part

## Preconditions

1. Created at least one Way

## Steps to reproduce

1. Create new Goal metric
2. Double click on markdown and enter link markdown with empty name part, e.g. `[](https://google.com)`

## Actual result

The Goal metric collapses to **div** with size 0x0 px. You cannot enter a Goal name.
![image](https://github.com/tritonJS826/masters-way/assets/4976837/369fe15d-1219-472d-8ea2-7262e255e844)

## Expected result

Spaces are trimmed and a placeholder is displayed
![image](https://github.com/tritonJS826/masters-way/assets/4976837/cdefb3b1-3d8d-45e9-a669-3d9ea087f2cd)

**or** a visually empty line is shown with full size clickable div
![image](https://github.com/tritonJS826/masters-way/assets/4976837/df5224c3-9161-4224-9cad-4f6e2b8e4204)

**or** automatically converted to custom placeholder
![image](https://github.com/tritonJS826/masters-way/assets/4976837/095443a8-b1e1-42ce-a74e-d50ac47dc7c7)

**Comment by Ekaterina1994** [comment]
[](https://google.com)

**Comment by Ekaterina1994** [comment]
It's standard behavior of markdown format.  Checked it in the previous comment. )))  Let's skip it for now

**Comment by tritonJS826** [comment]
automatically converted to custom placeholder is good enough

**Comment by Ekaterina1994** [comment]
Done in #935
