### ISSUE TITLE
user's ways: Markdown in Goal description shown incorrectly in Ways card view

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#938]
## Description

Markdown in Goal description shown incorrectly in Ways card view

## Preconditions

1. Create Way

## Steps to reproduce

1. Enter Goal description with e.g. `[**Lorem Ipsum**](https://example.com)`
![image](https://github.com/tritonJS826/masters-way/assets/4976837/4ac190df-df0a-4f31-b242-a05b16c514aa)

## Actual result

Markdown in Goal description shown incorrectly
![image](https://github.com/tritonJS826/masters-way/assets/4976837/2795b38b-9cc3-4d2e-8d40-bad2101ab03c)

## Expected result

Markdown in Goal description shown correctly
![image](https://github.com/tritonJS826/masters-way/assets/4976837/cceed288-e9e1-403e-86b0-eb0343687eb8)

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
