### ISSUE TITLE
Increase user activation

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#948]
Добавить выделенные зеленым пункты на home page 
 отсюда https://docs.google.com/document/d/15I9Yd8BvFdud_CV6CRy7bt1hI7AzK_FAqhgThScdSBg/edit?

**Comment by Ekaterina1994** [comment]
Archived. Updated texts according content maker's texts - https://docs.google.com/document/d/1ycaeT5-QxqiXjgQj5pRgXXX9cyjNo-KqSuieh0oeDg0/edit

**Comment by vdruda** [comment]
Done
