### ISSUE TITLE
Way status updates only after Ways page reload

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#952]
## Description

Way status updates only after Ways page reload.

## Preconditions

1. Create Way
2. Create some Goal metrics and leave it unchecked

## Steps to reproduce

_Way in status "In progress"_
1. Mark all Goal metrics as checked
2. Go to your profile and look at Ways  #section
3. After page loaded the Way still in "In progress" status but **all** Goal metrics marked as Done

![Image](https://github.com/tritonJS826/masters-way/assets/4976837/8d155f4c-04ab-4a19-b731-f000d23db49a)

4. Reload page (<kbd>F5</kbd> or <kbd>CTRL</kbd>+<kbd>F5</kbd>)
5. After page loaded the Way have "Complete" status

![Image](https://github.com/tritonJS826/masters-way/assets/4976837/ecbddc6f-fd50-43a4-87c7-d8cfe623a11e)

## Actual result

Correct Way status shown after page reload only

## Expected result

Correct status of the Way shown after Goal metrics changes without page reload

**Comment by tritonJS826** [comment]
@Ekaterina1994 i propose to update user data each time opening personal area (firstly show globally saved user data and than sent request and updated user data)

**Comment by Ekaterina1994** [comment]
@pp2amd6 Can't reproduce/ Please check

**Comment by pp2amd6** [comment]
Closed. The bug no longer reproduces
