### ISSUE TITLE
User which not signed in into Google account can't see image on Login popup

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#954]
## Description

User which not signed in into Google account can't see image on Login popup.
It happened because image not available if user not sign in into Google account.
![image](https://github.com/tritonJS826/masters-way/assets/4976837/fd065a0c-7662-4c4c-a8fe-3d9f9d119a05)

## Preconditions

1. Logout from [Google account](https://myaccount.google.com/)

## Steps to reproduce

1. Open any application page, e.g. [Home page](https://mastersway.netlify.app/)
2. Press Login button

## Actual result

Image on popup left side not loaded

## Expected result

Image on popup left side loaded

## Additional context
Proof of the cause of the bug:
1. Open browser in Incognito mode (Private mode)
3. Open [image link](https://lh3.google.com/u/0/d/1AF0qlh-KmFAtFILD9wCPw91OrZVZs8sH=w1361-h606-iv1)
4. Google Sign in page presented
![image](https://github.com/tritonJS826/masters-way/assets/4976837/5fc3d75d-303c-47d0-8972-ae7032f162e0)

5. Sign in into account with your credentials
6. Image will be displayed

**Comment by pp2amd6** [comment]
Update: after cache clearing any image stored on Google not loaded

**Comment by Ekaterina1994** [comment]
UPD: cach was cleaned

https://github.com/tritonJS826/masters-way/assets/57002521/baf44482-4f51-495d-8ac8-d10bd03aa658

**Comment by pp2amd6** [comment]
Bug not reproduce anymore
