### ISSUE TITLE
Сannot edit Goal metrics if link markup or image markup was used on Way page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#955]
## Description

Сannot edit Goal metrics if link markup or image markup was used on Way page.

## Preconditions

1. Create Way

## Steps to reproduce

1. Create new Goal metric and use link markup or image markup as content for record
Examples:
`[Link](https://google.com)` for link
`![](https://upload.wikimedia.org/wikipedia/commons/1/11/Test-Logo.svg)` for image

2. Double-click on the Goal metric area for going to editing mode (like Job, Plan, Problem, Comment)
![image](https://github.com/tritonJS826/masters-way/assets/4976837/6aad9d25-8349-4a37-b625-f39b2781b00f)

## Actual result

The recording entered edit mode when double-clicking on the Goal metric area

## Expected result

The entry has entered edit mode

## Additional context

Editing mode not working because editable area for Goal metric have content dimensions
![image](https://github.com/tritonJS826/masters-way/assets/4976837/5a93101d-5d94-44b7-bea7-86329a59776c)

At the same time, the editing mode works for Daily reports because the editable area inherits the width of the parent
![image](https://github.com/tritonJS826/masters-way/assets/4976837/5f547d75-923d-44ec-96ba-ec83b1d3adac)

**Comment by Ekaterina1994** [comment]
Done
