### ISSUE TITLE
Open Graph image path set as relative instead of absolute

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#956]
## Description

Open Graph image path set as relative instead of absolute
Accordingly to [Open Graph Protocol](https://ogp.me/) documentation `og:image` its URL:
> og:image - An image URL which should represent your object within the graph.

Open Graph documentation define [URL](https://ogp.me/#url) as:
> All valid URLs that utilize the https:// or https:// protocols

## Steps to reproduce

1. Open application URL
2. Open page as HTML code
3. Look at line 31 or find Open Graph meta tag in head section

## Actual result

Open Graph image have relative path
```html
<meta property="og:image" content="public/logo192x192.png">
```

## Expected result

Open Graph image have relative path, for example:
```html
<meta property="og:image" content="https://mastersway.netlify.app/logo192x192.png">
```

**Comment by Ekaterina1994** [comment]
According to the article the content for image is not require http path, but we don't have all OG tags, maybe need to add it
https://medium.com/nuances-of-programming/%D1%87%D1%82%D0%BE-%D1%82%D0%B0%D0%BA%D0%BE%D0%B5-open-graph-%D0%B8-%D0%BA%D0%B0%D0%BA-%D1%8F-%D0%BC%D0%BE%D0%B3%D1%83-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8%D1%82%D1%8C-%D0%B5%D0%B3%D0%BE-%D0%B4%D0%BB%D1%8F-%D1%81%D0%B2%D0%BE%D0%B5%D0%B3%D0%BE-%D0%B2%D0%B5%D0%B1-%D1%81%D0%B0%D0%B9%D1%82%D0%B0-be4e225bf080

**Comment by Ekaterina1994** [comment]
Done
