### ISSUE TITLE
Mentor/mentee relationship: the way is reflected as a follower for the page mentor, but the mentee has not yet confirmed the mentorship

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#957]

**Comment by n144astya** [comment]
Mentor page 

![Image](https://github.com/tritonJS826/masters-way/assets/142949669/dad39a44-b834-4ced-a4f8-1e6d7a8f97f0)

Mentee way 


![Image](https://github.com/tritonJS826/masters-way/assets/142949669/5930973f-8708-4121-ae42-6cf2576e9adb)

**Comment by n144astya** [comment]
Priority: medium
Severity: high

Environment : Windows 10 Version 22H2
Google Chrome  121.0.6167.161

Preconditions: 
mentor sent an application for mentoring way

Reproduction steps: 
1) open the way mentor for mentee

Actual result:
the way is reflected as a follower for the page mentor

Expected Result:
the way is not reflected as a follower for the page mentor

**Comment by n144astya** [comment]
I suggest a modal window "Mentors requests of this way" replaced by "I want mentoring this way"


![Image](https://github.com/tritonJS826/masters-way/assets/142949669/14a2c671-a9ec-4136-bf91-e866ac14185f)

**Comment by n144astya** [comment]
There is no notification that a mentor has been found for the mentee page. But for mentor page mentee can see notification 


![Image](https://github.com/tritonJS826/masters-way/assets/142949669/9b49e81a-7b49-4682-baa7-2326efdca0f4)

**Comment by Ekaterina1994** [comment]
Need more details. Sent video in TG

**Comment by n144astya** [comment]
It isn't bag.
