### ISSUE TITLE
Daily reports: Data entered flashes when saved

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#958]
Environment: Windows 10 Version 22H2, Google Chrome  121.0.6167.161

Preconditions
1) Log in to the system
2) Оpen any way

Steps:
1) Create new day report
2)Add new job done 
3) Write new job
4) Click on an empty field

Actual result;
"Empty markdown! Double click on me" appears and after that the entered reserve is saved
Expected Result 
The entered task is saved

Severity Low
Priority Low

https://www.awesomescreenshot.com/video/28128931?key=d7145f401d1fbe3a735c9c1e2438c705

**Comment by n144astya** [comment]
The same scenario occurs in the plan column

**Comment by Ekaterina1994** [comment]
@n144astya Can't reproduce, please check and add more details)

https://github.com/tritonJS826/masters-way/assets/57002521/40d6ecd1-19f4-436c-9229-ab58fe65c9be
