### ISSUE TITLE
Daily reports: entered data is not saved when you click on the "Add job done" button.

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#959]
Environment: Windows 10 Version 22H2, Google Chrome  121.0.6167.161

Preconditions
1) Log in to the system
2) Оpen any way

Steps:
1) Create new day report
2)Add new job done 
3) Write new job
4) Click on  the "Add job done" button

Actual result;
The information "Empty markdown! Double click on me" appears in the import field instead of the entered task
Expected Result 
The information in the entered field is saved. A new field has been created.

Severity Medium
Priority Medium
https://www.awesomescreenshot.com/video/28128931?key=d7145f401d1fbe3a735c9c1e2438c705

**Comment by n144astya** [comment]
The same scenario occurs in the plan column

**Comment by tritonJS826** [comment]
Can't reproduce, probalby was fixed during migration to MobX. Recheck required

**Comment by evgenia7p** [comment]
Checked
