### ISSUE TITLE
Daily report: not all requests are processed when click multiple times quickly to create a record

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#962]
Environment: Windows 10 Version 22H2, Google Chrome  121.0.6167.161

Preconditions
1) Log in to the system
2) Оpen any way

Steps:
1) Create new day report
2) Click multiple 8 times quickly to add new commente

Actual result;
2 comments created, 4 POST requests sent

Expected Result 
8 comments created

Severity medium
Priority medium

![Image](https://github.com/tritonJS826/masters-way/assets/142949669/7c98b438-9987-44e9-91ee-82d2aa8faa27)

**Comment by tritonJS826** [comment]
button blocked when making request but it is not visible for user, reassign on designers if needed

**Comment by Ekaterina1994** [comment]
Added cursor: not-allowed; while making request. I need design move card to the design column

**Comment by Ekaterina1994** [comment]
Done
