### ISSUE TITLE
Metrics: The cursor doubles when hovering over a metric, when crossing the field where the tooltip is displayed

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#964]
The doubling of the cursor is due to the layering of the "Not finished yet" tooltip on the field.
Doubling appears even without editing the metric, if the line tooltip is not located above the line it refers to. 

https://github.com/tritonJS826/masters-way/assets/142949669/e584684c-35f7-473e-9e7e-1cb98def2c8f

Environment: Windows 10 Version 22H2, Google Chrome  121.0.6167.161

Preconditions
1) Log in to the system
2) Open your way
3) Cread new goal metric  "Write test documentation for the about project page of a non-logged in user"

Steps:
1) Double click for goal metric  "Write test documentation for the about project page of a non-logged in user"
2) Click on the word  "about"

Actual result;
Before clicking on a word, the cursor doubled. The metric field is closed for editing

Expected Result 
The cursor is positioned at the word "about ". Metric field is editable

Severity Medium
Priority Medium

**Comment by Ekaterina1994** [comment]
Can't reproduce. Was fixed aumatically after refactor tooltip component. Please check

**Comment by vdruda** [comment]
The bug is reproducible, it needs to be fixed @Ekaterina1994

**Comment by Ekaterina1994** [comment]
@vdruda Can't reproduce. Need more details

**Comment by vdruda** [comment]
@Ekaterina1994 

1.Open Personal area 
2.Chose one of your way
3.Click button "Add new goal metric"
4.Write some in new metric 
5. Hover over an open metric without leaving it

https://github.com/tritonJS826/masters-way/assets/141385609/3c61b126-0562-4a3b-a716-f51806ecd4f0

**Comment by Ekaterina1994** [comment]
Тултип "Вставить" это не функциональность нашего приложения. Даже стили оличаются

https://github.com/tritonJS826/masters-way/assets/57002521/3d8a1ea5-dcbd-45fb-bc9e-20396463a358

**Comment by vdruda** [comment]
The bug can  be reproduced only on the local version.
