### ISSUE TITLE
Daily reports:  POST method does not display entered time changes in dialog when transferring plan to completed task

### ISSUE THREAD

**Issue by n144astya** [tritonJS826/masters-way#965]
Environment: Windows 10 Version 22H2, Google Chrome  121.0.6167.161

Preconditions
1) Log in to the system
2) Open your way
3) Cread new plans

Steps:
1) Cread new plans
2) Click 'Click to mark plan as completed.' checkbox to copy this planned job to 'Jobs done'.
3) In opened pop-up window, set 30 minutes in the “Estimation time” field 
4)  Click the botton 'Copy to jobs done'.здфт

Actual result;
The plan moves to the "Jobs Done" column. Elapsed time displays 0 minutes

Expected Result 
The plan moves to the "Jobs Done" column. Elapsed time displays 30 minutes

Severity Medium
Priority Medium

https://github.com/tritonJS826/masters-way/assets/142949669/3c77afe2-7002-4fda-b62e-c1c0939fb720

**Comment by n144astya** [comment]
**Response Headers:** 
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Content-Length
Content-Length: 322
Content-Type: application/json; charset=utf-8
Date: Thu, 30 May 2024 10:52:32 GMT

**Request headers:**
:authority: 34.82.43.122
:method: POST
:path: /api/jobDones
:scheme: https
Accept: */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Content-Length: 161
Content-Type: application/json
Origin: https://mastersway.netlify.app
Priority: u=1, i
Referer: https://mastersway.netlify.app/
Sec-Ch-Ua: "Google Chrome";v="125", "Chromium";v="125", "Not.A/Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

**Comment by Ekaterina1994** [comment]
Done
