### ISSUE TITLE
Goal way preview glitch in table view on pages with Ways list

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#968]
## Description

Goal way preview glitch in table view on pages with Ways list (user profile, All Ways).

## Preconditions

1. Log in into app
2. Create Way with long Goal description (was used 500 symbols accordingly [Restrictions](https://docs.google.com/spreadsheets/d/1rtwQJgdxyqh2uDWpNzCrxiUORe49oxISsd2shuq0UMU/edit#gid=0)) file

## Steps to reproduce

1. Go to User page
2. Hover mouse on Goal description
3. When preview element will be presented, scroll down

## Actual result

Page glitched

https://github.com/tritonJS826/masters-way/assets/4976837/96e5ba93-588b-4347-a174-824bfad31ef5

## Expected result

Preview element closed, page presented in normal state

https://github.com/tritonJS826/masters-way/assets/4976837/399ca2d0-d147-4fed-9fa9-7e847010dd72

## Additional context

Bug **reproduced** in: Google Chrome, Version 125.0.6422.113 (Official Build) (64-bit)
Bug **NOT reproduced** in: Mozilla Firefox, 126.0.1 (64-bit)

**Comment by Ekaterina1994** [comment]
Can't reproduce. Was fixed after refactor tooltip component/ Please check again

**Comment by vdruda** [comment]
Done
