### ISSUE TITLE
Day Reports: When you change the color of tags in Labels window, the tags displayed in statistics and in daily reports change only when the page is refreshed

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#972]
### Preconditions
User is authorized. User's way is created and opened. Some day reports with jobs done tags exist

### Steps
1. Click on button "Adjust job tags" 
2. Change a color of any tag 
3. Close the window of labels
4. Check if the color of tags displayed in statistics and in daily reports was changed
5. Refresh the page

### Expected result
Color of tags displayed in statistics and in daily reports is changed right after changings in Labels window

### Actual result
Color of tags displayed in statistics and in daily reports change only when the page is refreshed

https://github.com/tritonJS826/masters-way/assets/163824877/0c2fd8f6-10c2-45bd-9212-e12a003b8039

**Comment by evgenia7p** [comment]
Checked

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
