### ISSUE TITLE
Day Reports: Job labels consisting of a word with 14 or more letters are not completely visible in Labels window

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#973]
## Preconditions
User is authorized. User's way is created and opened

## Steps
1. Click on button "Adjust job tags". 
2. Click on "Add tag" in the opened window. 
3. Type a word of 14 or more letters
4. Click on "Ok"

## Expected result
Full word is displayed

## Actual result
It is impossible to read the full word

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/227ca36a-0f56-4185-a91c-55f1ae5ccfe1)

**Comment by tritonJS826** [comment]
good case, Ekaterina, let's add few more letters, 18 for example

**Comment by tritonJS826** [comment]
lets change it to 30

**Comment by kladweb** [comment]
I think 20 letters is enough. No ?

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
