### ISSUE TITLE
Day Reports: Button “Cancel” and the cross in the dialog box that occurs when clicking on the check box in Plans block, doesn’t work correctly

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#976]
Preconditions
User is authorized. User's way is created and opened. Some day reports with plans exist 

Steps
1.	Click on the check box next to any written plan in Plans block to mark it as completed
2.	Click on “Cancel” button in the dialog box
3.	Repeat with clicking on the cross 

Expected result
Plan isn’t marked as completed

Actual result
Plan is marked as completed

https://github.com/tritonJS826/masters-way/assets/163824877/83824494-9803-4f26-bcc7-586010cee697

https://github.com/tritonJS826/masters-way/assets/163824877/b73cd1c0-c1b0-47d2-b8ab-4262108c5c71

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
