### ISSUE TITLE
Day Reports: Changes of description and estimation time are not saved when you copy the planned job to "Jobs done"

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#977]
Preconditions
User is authorized. User's way is created and opened. Day report with filled plan exists (with description and estimation time) 

Steps
1. Click 'Click to mark plan as completed' checkbox to copy the planned job to 'Jobs done'.
2. In opened dialog box change description and estimation time 
3. Click 'Copy to jobs done'

Expected result
Planned job with its editing is copied to 'Jobs done'

Actual result
Planned job is copied to 'Jobs done' but any changes of description and estimation time are not saved

https://github.com/tritonJS826/masters-way/assets/163824877/97d40ca5-e4a6-4203-a0c8-5b8d21cdffda

**Comment by Ekaterina1994** [comment]
@evgenia7p PLease check, is it duplicate of issue #965 ?

**Comment by evgenia7p** [comment]
> [@evgenia7p](https://github.com/evgenia7p) PLease check, is it duplicate of issue [#965](https://github.com/tritonJS826/masters-way/issues/965) ?

@Ekaterina1994 Probably these two issues are similar partly, but this issue has additional info about the description. How do I make it better? Should I add comments to issue 965 and close this issue?

**Comment by Ekaterina1994** [comment]
Done in #965

**Comment by evgenia7p** [comment]
Checked
