### ISSUE TITLE
Navigation menu: Navigation menu doesn’t close after clicking on the Mastersway icone

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#984]
Steps
1.	Click Menu button on the right side of the Нeader
2.	Click on the Mastersway icone in the Navigation menu

Expected result
1.	The main page opens
2.	The Navigation menu closes automatically

Actual result
1.	The main page opens
2.	The Navigation menu doesn’t close automatically

https://github.com/tritonJS826/masters-way/assets/163824877/ecb9bd6f-d1c5-4de1-953f-b7ad7033e52d

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
