### ISSUE TITLE
Different day report amount on different pages. Should be the same

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#988]
Ask @Ekaterina1994  for details

**Comment by Ekaterina1994** [comment]
https://github.com/tritonJS826/masters-way/assets/57002521/bbec41cf-adea-42a1-b23a-1ba995c5934b

**Comment by Moon1it** [comment]
Ссылка на видео:
https://drive.google.com/file/d/1LzwARDz-U50c66v-munYDnT12T0cN9s2/view?usp=sharing

**Comment by tritonJS826** [comment]
@Ekaterina1994 add comment please

1. We should add restriction to the back end
2. Think about the logic related to dates

**Comment by Moon1it** [comment]
Done

**Comment by vdruda** [comment]
Done
