### ISSUE TITLE
Accessibility: theme switch button has no value text on Home page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#989]
## Description

Theme switch button has no value text on Home page. Accordingly to [WCAG](https://www.w3.org/TR/WCAG22/#non-text-content) descriptive text must be presented to screen reader users to indicate the function of the button.
![image](https://github.com/tritonJS826/masters-way/assets/4976837/27f2392d-fd10-479f-8782-e5e9f8529003)

## Steps to reproduce

1. Open Home page
2. View HTML code for theme switch button element

## Actual result

Theme switch button has no value text
```html
<button class="_iconWrapper_c6yhs_1 _themeSwitcher_15ikq_86" style="">...</button>
```

## Expected result

Theme switch button has value text

**Comment by Ekaterina1994** [comment]
Need to add aria-label attribute instead of text value for icon button. Also need to research do we need to use this attribute to all buttons (where we use text value)? or only for icon buttons

**Comment by pp2amd6** [comment]
> Also need to research do we need to use this attribute to all buttons (where we use text value)? or only for icon buttons

Only for icons because screen readers can read textContent for button tag.

> The button has an accessible label. By default, the accessible name is computed from any text content inside the button element. However, it can also be provided with [aria-labelledby](https://w3c.github.io/aria/#aria-labelledby) or [aria-label](https://w3c.github.io/aria/#aria-label).

**Comment by Ekaterina1994** [comment]
Done
