### ISSUE TITLE
Accessibility: Social media buttons has no value text on Home page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#990]
## Description
Social media buttons has no value text on Home page. Accordingly to [WCAG](https://www.w3.org/TR/WCAG22/#non-text-content) descriptive text must be presented to screen reader users to indicate the function of the button.
![image](https://github.com/tritonJS826/masters-way/assets/4976837/141a85f8-1510-4aea-a235-fbb57e449276)

## Steps to reproduce

1. Open Home page
2. View HTML code for social media buttons element

## Actual result

Social media buttons has no value text

```html
<a class="_link_lef6t_1" rel="noopener noreferrer" href="https://linkedin.com/company/masters-way-project" target="_blank">...</a>
```

## Expected result

Social media buttons has value text, for example `aria-label`

```html
<a class="_link_lef6t_1" rel="noopener noreferrer" href="https://linkedin.com/company/masters-way-project" target="_blank" aria-label="Master's Way LinkedIn page">...</a>
```

**Comment by Ekaterina1994** [comment]
#989 and #991

**Comment by Ekaterina1994** [comment]
Done

**Comment by n144astya** [comment]
Done
