### ISSUE TITLE
Accessibility: right side navigation menu buttons not have accessible name on Home page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#991]
## Description

Right side navigation menu buttons not have accessible name on Home page. Accordingly to [WCAG](https://www.w3.org/TR/WCAG21/#name-role-value) ARIA command elements must have discernible text that clearly describes the destination, purpose, function, or action for screen reader users.

![image](https://github.com/tritonJS826/masters-way/assets/4976837/6875bcf2-0f94-4393-956d-ac00a8f39d4c)

## Steps to reproduce

1. Open Home page
2. View HTML code for right side navigation menu buttons

## Actual result

Right side navigation menu buttons not have accessible name
```html
<div role="button" type="button" aria-haspopup="dialog" aria-expanded="false" aria-controls="radix-:r4:" data-state="closed">...</div>
```

## Expected result

Right side navigation menu buttons have accessible name, for example `aria-label`
```html
<div role="button" type="button" aria-haspopup="dialog" aria-expanded="false" aria-controls="radix-:r4:" data-state="closed" aria-label="Navigation menu">...</div>
```

**Comment by Ekaterina1994** [comment]
#989 and #990

**Comment by Ekaterina1994** [comment]
Done

**Comment by n144astya** [comment]
Done
