### ISSUE TITLE
Day reports: Clicking outside the Job author's name loads the user's page on Way page

### ISSUE THREAD

**Issue by pp2amd6** [tritonJS826/masters-way#992]
## Description

Clicking outside the Job author's name loads the user's page on Way page
![image](https://github.com/tritonJS826/masters-way/assets/4976837/c075fd65-f48e-4bed-913e-53190774949d)

## Preconditions

1. Open Way page
2. Create Day report
3. Create Job

## Steps to reproduce

1. Click outside the Job author's name
![image](https://github.com/tritonJS826/masters-way/assets/4976837/0f3a7166-f7f5-42e8-8cfa-b9dde46faefa)

## Actual result

Job author profile page loaded

## Expected result

Nothing happened

**Comment by Ekaterina1994** [comment]
Done
