### ISSUE TITLE
Adjust pnpm monorepo

### ISSUE THREAD

**Issue by tritonJS826** [tritonJS826/masters-way#993]
- [ ] install concurrently to the root instead using pnpm dlx
- [ ] move main scripts (for husky, starting project, etc) to the root 
- [ ] adjust caching for modules (if possible), make 3 groups of precommit scripts for husky: 1 - running when change mw-webapp module, 2 - running when changed mw-server, 3 - running always (e2e test in mw-webapp)
- [ ] you can also provide additional ideas related to improving dev experience

**Comment by Ekaterina1994** [comment]
Done
