### ISSUE TITLE
Language: Names and positions of the team members in “About our project” section are not translated into Russian, Ukrainian and Georgian languages

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#994]
Steps
1.	Open "About our project" page
2.	Russian language chosen
3.	Ukranian language chosen
4.	Georgian language chosen

Expected result
The section interface "About our project" is translated into Russian, Ukrainian and Georgian languages

Actual result
Names and poditions of the team members are not translated into Russian, Ukrainian and Georgian languages

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/72c80a59-2eb2-4b0f-a46b-dc437e334b93)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/f44dd2a5-2f8e-43e8-82c6-14e8d5cf3b62)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/922c4ec4-2c3a-4cb1-85d5-72de842682c2)

**Comment by tritonJS826** [comment]
Let's skip it!

**Comment by evgenia7p** [comment]
> Let's skip it! it's hard to translate names and usually it is not obvious how to translate role (QA Engineer- Инденер по обуспечению качества- looks a little strange maybe)

@tritonJS826 I might not fully agree with this statement. We can write QA-инженер at least, beacuse it looks weird when the whole application in Russian, Ukranian and Georgian languages and only one block is totally in English. But I understand that this is not a priority issue, so I will close it.
