### ISSUE TITLE
Language: “Way of” in “All ways” section is not translated into Russian, Ukrainian and Georgian languages

### ISSUE THREAD

**Issue by evgenia7p** [tritonJS826/masters-way#995]
Steps
1.	Open All ways page
2.	Russian language chosen
3.	Ukranian language chosen
4.	Georgian language chosen

Expected result
The section interface " All ways " page is translated into Russian, Ukrainian and Georgian languages

Actual result
“Way of” in each ways is not translated into Russian, Ukrainian and Georgian languages

![Image](https://github.com/tritonJS826/masters-way/assets/163824877/fcf6038c-64c3-463e-a01e-025cf29cbc1e)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/bc865719-09a6-4dbd-aeec-841aac9955a2)
![Image](https://github.com/tritonJS826/masters-way/assets/163824877/d40d0be2-13f4-4821-b521-a47a0cda3f9d)

**Comment by Ekaterina1994** [comment]
Done

**Comment by evgenia7p** [comment]
Checked
